# All NBA_py Functions
Walking through each function in nba_py
<br>
Official documentation available here: https://nba-py.readthedocs.io/en/latest/#

In [1]:
import os
import pandas as pd
import nba_py as nba
from nba_py import team
from nba_py import game
from nba_py import player

## Scoreboard
* Uses: get game_ids by date, standings over time, season series information

In [10]:
nba.Scoreboard(month=12, day = 25, year= 2018, league_id = '00', offset = 0).available()

      GAME_ID  PT_AVAILABLE
0  0021800501             1
1  0021800499             1
2  0021800498             1
3  0021800500             1
4  0021800497             1

### Available Methods
* available()
* east_conf_standings_by_day()
* game_header()
* last_meeting()
* line_score()
* series_standings()
* west_conf_standings_by_day()

# Team Module

## Team List
* Uses: getting team_ids and abbreviations

In [109]:
team.TeamList(league_id='00').info().head(5)

  LEAGUE_ID     TEAM_ID MIN_YEAR MAX_YEAR ABBREVIATION
0        00  1610612737     1949     2019          ATL
1        00  1610612738     1946     2019          BOS
2        00  1610612739     1970     2019          CLE
3        00  1610612740     2002     2019          NOP
4        00  1610612741     1966     2019          CHI

## Team Clutch Splits
* Uses: Team performance at end of game scenarios
* Check out all the arguments in the documentation because you can get very specific in your pulls

In [19]:
bos_id = 1610612738

In [21]:
team.TeamClutchSplits(bos_id, league_id = '00', season= '2018-19').last10sec_deficit_3point()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Last 10 SEC <= 3 PTS,2018-19,13,6,7,0.462,0.2,0.3,0.8,0.4,...,1,1,1,1,1,1,1,1,137,2018-19

### Available Methods
* last10sec_deficit_3point()
* last1min_deficit_5point()
* last1min_plusminus_5point()
* last30sec_deficit_3point()
* last30sec_plusminus_5point()
* last3min_deficit_5point()
* last3min_plusminus_5point()
* last5min_deficit_5point()
* last5min_plusminus_5point()

## Team Common Roster
* Uses: Getting the roster and coaching staff

In [22]:
team.TeamCommonRoster(bos_id, season= '2017-18').roster()

,TeamID,SEASON,LeagueID,PLAYER,NUM,POSITION,HEIGHT,WEIGHT,BIRTH_DATE,AGE,EXP,SCHOOL,PLAYER_ID
0,1610612738,2017,00,Jayson Tatum,0,F,6-8,205,"MAR 03, 1998",20.0,R,Duke,1628369
1,1610612738,2017,00,Jaylen Brown,7,G-F,6-7,225,"OCT 24, 1996",21.0,1,California,1627759
2,1610612738,2017,00,Shane Larkin,8,G,5-11,175,"OCT 02, 1992",25.0,3,Miami,203499
3,1610612738,2017,00,Xavier Silas,9,G,6-5,205,"JAN 22, 1988",30.0,1,Northern Illinois,202918
4,1610612738,2017,00,Kyrie Irving,11,G,6-3,193,"MAR 23, 1992",26.0,6,Duke,202681
5,1610612738,2017,00,Terry Rozier,12,G,6-2,190,"MAR 17, 1994",24.0,2,Louisville,1626179
6,1610612738,2017,00,Marcus Morris,13,F,6-9,235,"SEP 02, 1989",28.0,6,Kansas,202694
7,1610612738,2017,00,Gordon Hayward,20,F,6-8,226,"MAR 23, 1990",28.0,7,Butler,202330
8,1610612738,2017,00,Jabari Bird,26,G,6-6,198,"JUL 03, 1994",23.0,R,California,1628444
9,1610612738,2017,00,Daniel Theis,27,F-C,6-9,243,"APR 04, 1992",26.0,R,,1628464
10,1610612738,2017,00,Abdel Nader,28,F,6-6,230,"SEP 25, 1993",24.0,R,Iowa State,1627846
11,1610612738,2017,00,Guerschon Yabusele,30,F,6-8,260,"DEC 17, 1995",22.0,R,,1627824
12,1610612738,2017,00,Marcus Smart,36,G,6-4,220,"MAR 06, 1994",24.0,3,Oklahoma State,203935
13,1610612738,2017,00,Semi Ojeleye,37,F,6-7,235,"DEC 05, 1994",23.0,R,Southern Methodist,1628400
14,1610612738,2017,00,Al Horford,42,F-C,6-10,245,"JUN 03, 1986",32.0,10,Florida,201143
15,1610612738,2017,00,Kadeem Allen,45,G,6-3,200,"JAN 15, 1993",25.0,R,Arizona,1628443
16,1610612738,2017,00,Aron Baynes,46,C,6-10,260,"DEC 09, 1986",31.0,5,Washington State,203382
17,1610612738,2017,00,Greg Monroe,55,C-F,6-11,265,"JUN 04, 1990",28.0,7,Georgetown,202328
18,1610612738,2017,00,Jonathan Gibson,60,G,6-2,185,"NOV 08, 1987",30.0,1,New Mexico State,1626780

### Available Methods
* roster()
* coaches()

## Team Details
* Uses: Getting team championships, history, hall of famers, retired numbers, etc.

In [23]:
team.TeamDetails(bos_id).awards_championships()

    YEARAWARDED            OPPOSITETEAM
0          1957         St. Louis Hawks
1          1959      Minneapolis Lakers
2          1960         St. Louis Hawks
3          1961         St. Louis Hawks
4          1962      Los Angeles Lakers
5          1963      Los Angeles Lakers
6          1964  San Francisco Warriors
7          1965      Los Angeles Lakers
8          1966      Los Angeles Lakers
9          1968      Los Angeles Lakers
10         1969      Los Angeles Lakers
11         1974         Milwaukee Bucks
12         1976            Phoenix Suns
13         1981         Houston Rockets
14         1984      Los Angeles Lakers
15         1986         Houston Rockets
16         2008      Los Angeles Lakers

### Available Methods
* awards_championships()
* awards_conf()
* awards_div()
* background()
* history()
* hof()
* retired()
* social_sites()

## Team Game Logs
* uses: pulling game logs

In [28]:
team.TeamGameLogs(bos_id, season= '2018-19', season_type = "Regular Season").info().head(3)

,Team_ID,Game_ID,GAME_DATE,MATCHUP,WL,W,L,W_PCT,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1610612738,0021801211,"APR 09, 2019",BOS @ WAS,W,49,33,0.598,240,45,...,0.478,13,37,50,27,10,3,5,17,116
1,1610612738,0021801203,"APR 07, 2019",BOS vs. ORL,L,48,33,0.593,240,42,...,0.857,6,33,39,28,9,4,13,19,108
2,1610612738,0021801183,"APR 05, 2019",BOS @ IND,W,48,32,0.600,240,48,...,0.875,7,42,49,27,7,6,11,15,117

### Available Methods
* info()

## Team General Splits
* Uses: Pulling team performance for home v away, monthly, by days rest, etc

In [29]:
team.TeamGeneralSplits(bos_id, season= '2018-19').days_rest()

,GROUP_SET,GROUP_VALUE,TEAM_DAYS_REST_RANGE,GP,W,L,W_PCT,MIN,FGM,FGA,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Days Rest,0 Days Rest,0 Days Rest,13,5,8,0.385,48.0,38.5,87.2,...,6,4,6,1,4,5,5,6,152,0 Days Rest
1,Days Rest,1 Days Rest,1 Days Rest,51,32,19,0.627,48.3,43.1,90.8,...,3,2,4,3,2,4,3,4,152,1 Days Rest
2,Days Rest,2 Days Rest,2 Days Rest,13,9,4,0.692,48.4,41.4,91.6,...,5,6,5,4,3,2,4,5,152,2 Days Rest
3,Days Rest,3 Days Rest,3 Days Rest,2,1,1,0.500,48.0,43.5,88.5,...,4,3,1,2,5,3,2,2,152,3 Days Rest
4,Days Rest,4 Days Rest,4 Days Rest,1,1,0,1.000,48.0,49.0,92.0,...,1,5,3,6,6,1,1,1,152,4 Days Rest
5,Days Rest,6+ Days Rest,6+ Days Rest,2,1,1,0.500,48.0,40.5,99.5,...,2,1,2,5,1,6,6,3,152,6+ Days Rest

### Available Methods
* days_rest()
* location()
* monthly()
* pre_post_all_star()
* wins_losses()

## Team In Game Splits
* Uses: Split team performance by period, half, and scoring margin

In [30]:
team.TeamInGameSplits(bos_id, season = '2018-19').by_actual_margin()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,By Actual Margin,Behind more than 20 Points,13,2,11,0.154,4.9,4.3,9.8,0.438,...,2,10,5,2,2,5,10,2,147,Behind more than 20 Points
1,By Actual Margin,Behind 16 - 20 Points,22,6,16,0.273,5.9,5.7,12.5,0.460,...,3,8,10,11,3,6,7,1,147,Behind 16 - 20 Points
2,By Actual Margin,Behind 11 - 15 Points,34,9,25,0.265,7.8,7.4,15.6,0.472,...,4,5,9,5,8,3,4,3,147,Behind 11 - 15 Points
3,By Actual Margin,Behind 6 - 10 Points,51,19,32,0.373,7.3,6.4,14.4,0.446,...,8,7,7,10,5,8,6,7,147,Behind 6 - 10 Points
4,By Actual Margin,Behind 1 - 5 Points,73,40,33,0.548,8.7,8.0,17.7,0.452,...,6,6,4,6,6,7,3,4,147,Behind 1 - 5 Points
5,By Actual Margin,Tied,82,49,33,0.598,2.6,2.4,5.1,0.481,...,1,11,11,1,1,11,11,6,147,Tied
6,By Actual Margin,Ahead 1 - 5 Points,79,49,30,0.620,10.8,9.8,19.9,0.494,...,10,1,3,7,9,1,1,5,147,Ahead 1 - 5 Points
7,By Actual Margin,Ahead 6 - 10 Points,67,49,18,0.731,9.7,7.8,17.1,0.458,...,9,3,2,8,10,2,2,11,147,Ahead 6 - 10 Points
8,By Actual Margin,Ahead 11 - 15 Points,51,39,12,0.765,6.5,5.1,11.1,0.456,...,7,9,8,3,4,10,9,9,147,Ahead 11 - 15 Points
9,By Actual Margin,Ahead 16 - 20 Points,32,28,4,0.875,6.7,5.7,11.8,0.478,...,5,4,6,4,7,9,8,8,147,Ahead 16 - 20 Points
10,By Actual Margin,Ahead more than 20 Points,23,22,1,0.957,9.9,7.2,16.7,0.433,...,11,2,1,9,11,4,5,10,147,Ahead more than 20 Points

### Available Methods
* by_actual_margin()
* by_half()
* by_period()
* by_score_margin()

## Team Last N Games Splits
Uses: View team performance splits on prior games

In [35]:
team.TeamLastNGamesSplits(bos_id, season= '2018-19').gamenumber()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Game Number,Games 1-10,10,6,4,0.6,48.0,38.4,89.2,0.430,...,5,9,4,1,9,2,9,5,158,Games 1-10
1,Game Number,Games 11-20,10,4,6,0.4,49.0,40.4,91.1,0.443,...,7,1,4,7,5,4,8,6,158,Games 11-20
2,Game Number,Games 21-30,10,8,2,0.8,48.5,45.0,92.7,0.485,...,5,1,3,5,8,3,1,1,158,Games 21-30
3,Game Number,Games 31-40,10,7,3,0.7,48.5,42.8,88.7,0.483,...,4,3,6,2,6,5,2,2,158,Games 31-40
4,Game Number,Games 41-50,10,6,4,0.6,48.0,41.4,90.8,0.456,...,9,7,1,8,2,6,6,4,158,Games 41-50
5,Game Number,Games 51-60,10,6,4,0.6,48.0,44.5,91.9,0.484,...,2,5,2,3,3,7,3,3,158,Games 51-60
6,Game Number,Games 61-70,10,6,4,0.6,48.0,42.6,89.2,0.478,...,8,6,8,4,7,1,4,7,158,Games 61-70
7,Game Number,Games 71-80,10,5,5,0.5,48.0,41.3,89.9,0.459,...,3,8,6,5,4,8,7,8,158,Games 71-80
8,Game Number,Games 81+,2,1,1,0.5,48.0,43.5,94.0,0.463,...,1,3,8,8,1,9,5,9,158,Games 81+

### Available Methods
* gamenumber()
* last10()
* last15()
* last20()
* last5()

## TeamLineups
Use: pull stats for differing groups of on court players

In [39]:
team.TeamLineups(bos_id, season = '2018-19').lineups()

,GROUP_SET,GROUP_ID,GROUP_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,Lineups,-202954-1626154-1628400-1628408-1629057-,B. Wanamaker - R. Hunter - S. Ojeleye - P. Doz...,1,1,0,1.000,14.0,15.0,28.0,...,1,1,415,4,3,503,513,2,1,1
1,Lineups,-202330-202681-203935-1628369-1628400-,G. Hayward - K. Irving - M. Smart - J. Tatum -...,1,0,1,0.000,12.6,10.0,26.0,...,2,4,518,1,154,532,533,2,3,458
2,Lineups,-201143-202681-202694-203935-1628369-,A. Horford - K. Irving - M. Morris - M. Smart ...,43,24,19,0.558,11.7,11.4,22.6,...,3,3,529,4,13,502,530,9,4,92
3,Lineups,-201143-202330-202681-1628369-1628400-,A. Horford - G. Hayward - K. Irving - J. Tatum...,1,1,0,1.000,8.6,9.0,16.0,...,6,2,415,1,3,503,525,102,5,2
4,Lineups,-202681-202694-203935-1626179-1628369-,K. Irving - M. Morris - M. Smart - T. Rozier -...,1,1,0,1.000,8.5,9.0,19.0,...,6,140,1,198,154,503,354,1,2,4
5,Lineups,-1626179-1627759-1627824-1628400-1629057-,T. Rozier - J. Brown - G. Yabusele - S. Ojeley...,1,1,0,1.000,8.0,7.0,19.0,...,10,8,1,19,154,1,525,102,11,532
6,Lineups,-202694-1626179-1627759-1627824-1628369-,M. Morris - T. Rozier - J. Brown - G. Yabusele...,1,0,1,0.000,7.7,9.0,13.0,...,6,4,518,198,14,527,473,102,7,14
7,Lineups,-203382-1626179-1627759-1628369-1628400-,A. Baynes - T. Rozier - J. Brown - J. Tatum - ...,1,1,0,1.000,7.4,5.0,10.0,...,10,19,415,1,154,503,473,5,8,7
8,Lineups,-201143-202330-202681-1627759-1628369-,A. Horford - G. Hayward - K. Irving - J. Brown...,21,12,9,0.571,6.9,5.7,13.1,...,16,16,517,15,45,450,509,23,13,175
9,Lineups,-202330-202694-202954-203382-1628369-,G. Hayward - M. Morris - B. Wanamaker - A. Bay...,1,1,0,1.000,6.6,8.0,17.0,...,4,8,415,4,14,1,473,24,9,7
10,Lineups,-202954-1627759-1627824-1628369-1628464-,B. Wanamaker - J. Brown - G. Yabusele - J. Tat...,1,0,1,0.000,6.4,10.0,16.0,...,10,8,415,19,1,527,532,102,6,3
11,Lineups,-202954-1627759-1627824-1628400-1628464-,B. Wanamaker - J. Brown - G. Yabusele - S. Oje...,1,1,0,1.000,6.2,4.0,9.0,...,10,48,533,198,154,527,513,102,25,488
12,Lineups,-202954-1627759-1627824-1628400-1629057-,B. Wanamaker - J. Brown - G. Yabusele - S. Oje...,1,1,0,1.000,6.2,5.0,11.0,...,6,19,530,198,1,1,531,102,25,488
13,Lineups,-202954-1626154-1628400-1628408-1628464-,B. Wanamaker - R. Hunter - S. Ojeleye - P. Doz...,1,1,0,1.000,6.0,7.0,14.0,...,21,7,1,19,154,1,513,24,9,20
14,Lineups,-202681-202694-203935-1628369-1629057-,K. Irving - M. Morris - M. Smart - J. Tatum - ...,5,2,3,0.400,5.9,5.0,11.0,...,20,19,511,19,12,425,508,19,15,155
15,Lineups,-202954-1627824-1628400-1628408-1629057-,B. Wanamaker - G. Yabusele - S. Ojeleye - P. D...,1,1,0,1.000,5.8,6.0,15.0,...,4,48,1,198,3,1,473,102,12,6
16,Lineups,-202330-203382-1626179-1628369-1628400-,G. Hayward - A. Baynes - T. Rozier - J. Tatum ...,1,1,0,1.000,5.6,4.0,12.0,...,10,19,415,198,14,503,513,287,35,180
17,Lineups,-202330-202694-1626179-1628369-1629057-,G. Hayward - M. Morris - T. Rozier - J. Tatum ...,1,0,1,0.000,5.6,2.0,12.0,...,17,294,415,19,3,533,473,10,105,520
18,Lineups,-201143-202330-202954-1626179-1628369-,A. Horford - G. Hayward - B. Wanamaker - T. Ro...,1,1,0,1.000,5.4,3.0,10.0,...,21,19,415,19,14,1,513,5,35,14
19,Lineups,-202954-1626179-1627824-1628408-1628464-,B. Wanamaker - T. Rozier - G. Yabusele - P. Do...,1,1,0,1.000,5.3,4.0,10.0,...,131,19,415,19,154,503,473,102,35,520
20,Lineups,-202330-1626179-1627824-1628369-1628464-,G. Hayward - T. Rozier - G. Yabusele - J. Tatu...,1,1,0,1.000,5.3,5.0,13.0,...,35,48,415,198,154,1,513,102,35,510
21,Lineups,-201143-203382-203935-1626179-1628369-,A. Horford - A. Baynes - M. Smart - T. Rozier ...,3,2,1,0.667,5.0,4.3,10.0,...,35,40,381,19,45,1,467,21,33,158
22,Lineups,-201143-203935-1626179-1628369-1628400-,A. Horford - M. Smart - T. Rozier - J. Tatum -...,2,1,1,0.500,4.9,3.5,8.0,...,21,14,518,198,57,1,354,65,44,142
23,Lineups,-202330-202954-1627759-1628400-1628464-,G. Hayward - B. Wanamaker - J. Brown - S. Ojel...,5,3,2,0.600,4.9,4.6,9.4,...,19,15,516,14,51,1,512,24,23,30
24,Lineups,-202330-1626179-1627759-1628369-1628464-,G. Hayward - T. Rozier - J. Brown - J. Tatum -...,18,9,9,0.500,4.8,4.3,9.3,...,32,18,415,17,84,496,472,53,24,49
25,Lineups,-201143-202330-202694-1626179-1628400-,A. Horford - G. Hayward - M. Morris - T. Rozie...,1,1,0,1.000,4.7,4.0,8.0,...,35,19,415,19,154,1,473,24,35,50
26,Lineups,-202330-1626179-1627759-1628400-1629057-,G. Hayward - T. Rozier - J. Brown - S. Ojeleye...,3,1,2,0.333,4.7,4.0,8.3,...,30,17,502,19,90,499,441,10,31,81
27,Lineups,-201143-202681-203382-203935-1628369-,A. Horford - K. Irving - A. Baynes - M. Smart ...,14,9,5,0.643,4.6,4.4,7.7,...,31,34,501,67,80,468,448,88,18,43
28,Lineups,-1626179-1627824-1628400-1628464-1629057-,T. Rozier - G. Yabusele - S. Ojeleye - D. Thei...,1,0,1,0.000,4.6,2.0,8.0,...,10,48,415,198,3,527,354,10,46,180
29,Lineups,-1626179-1627759-1627824-1628408-1629057-,T. Rozier - J. Brown - G. Yabusele - P. Dozier...,1,1,0,1.000,4.5,6.0,9.0,...,61,48,518,4,154,1,354,102,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,Lineups,-202694-202954-203382-203935-1628369-,M. Morris - B. Wanamaker - A. Baynes - M. Smar...,2,2,0,1.000,1.2,1.0,2.0,...,234,140,342,97,154,1,273,287,254,102
221,Lineups,-1626179-1627759-1628369-1628400-1628464-,T. Rozier - J. Brown - J. Tatum - S. Ojeleye -...,4,3,1,0.750,1.2,0.0,2.3,...,227,294,296,198,154,432,434,223,344,488
222,Lineups,-201143-202681-203382-1626179-1627759-,A. Horford - K. Irving - A. Baynes - T. Rozier...,4,2,2,0.500,1.1,1.3,2.3,...,234,210,342,198,154,1,273,275,203,169
223,Lineups,-201143-202681-1626179-1627759-1628369-,A. Horford - K. Irving - T. Rozier - J. Brown ...,12,6,6,0.500,1.1,1.2,2.0,...,232,210,331,197,134,399,312,255,235,102
224,Lineups,-201143-202681-1626179-1628369-1628400-,A. Horford - K. Irving - T. Rozier - J. Tatum ...,2,1,1,0.500,1.1,1.0,3.0,...,195,230,1,97,154,1,273,223,213,50
225,Lineups,-202681-1626179-1627759-1628400-1628464-,K. Irving - T. Rozier - J. Brown - S. Ojeleye ...,7,2,5,0.286,1.1,0.9,1.6,...,234,282,376,188,154,412,309,183,213,102
226,Lineups,-202694-203382-203935-1628369-1628400-,M. Morris - A. Baynes - M. Smart - J. Tatum - ...,3,2,1,0.667,1.1,0.7,2.0,...,328,220,381,70,154,1,1,262,246,158
227,Lineups,-202694-203935-1626179-1627759-1628464-,M. Morris - M. Smart - T. Rozier - J. Brown - ...,8,3,5,0.375,1.1,0.6,1.9,...,233,263,321,191,154,1,351,223,299,442
228,Lineups,-201143-202330-202694-1627759-1628369-,A. Horford - G. Hayward - M. Morris - J. Brown...,3,2,1,0.667,1.0,0.7,2.0,...,131,266,305,147,154,1,318,102,254,102
229,Lineups,-201143-202681-203382-203935-1627759-,A. Horford - K. Irving - A. Baynes - M. Smart ...,7,5,2,0.714,1.0,0.6,1.4,...,287,257,303,162,154,1,250,220,254,378
230,Lineups,-202330-202681-202694-203382-1626179-,G. Hayward - K. Irving - M. Morris - A. Baynes...,8,6,2,0.750,1.0,0.9,1.4,...,234,263,342,198,145,1,351,223,244,169
231,Lineups,-202681-203382-203935-1626179-1627759-,K. Irving - A. Baynes - M. Smart - T. Rozier -...,3,2,1,0.667,1.0,0.7,1.7,...,292,266,381,70,154,1,318,206,254,180
232,Lineups,-202681-202694-1626179-1627759-1628369-,K. Irving - M. Morris - T. Rozier - J. Brown -...,3,1,2,0.333,1.0,0.7,3.3,...,292,266,305,198,90,1,441,287,298,509
233,Lineups,-201143-202330-202681-1626179-1628400-,A. Horford - G. Hayward - K. Irving - T. Rozie...,5,4,1,0.800,0.9,0.4,1.8,...,300,259,293,198,154,425,240,287,336,450
234,Lineups,-201143-202694-203935-1627759-1628369-,A. Horford - M. Morris - M. Smart - J. Brown -...,5,3,2,0.600,0.9,0.8,1.2,...,288,207,323,138,154,1,313,282,297,438
235,Lineups,-202694-202954-1626179-1627759-1628464-,M. Morris - B. Wanamaker - T. Rozier - J. Brow...,4,1,3,0.250,0.9,0.5,1.8,...,302,294,1,66,154,1,273,223,254,375
236,Lineups,-202694-1626179-1628369-1628400-1628464-,M. Morris - T. Rozier - J. Tatum - S. Ojeleye ...,3,2,1,0.667,0.9,0.7,1.7,...,292,220,1,198,154,1,251,262,303,381
237,Lineups,-202681-202694-203935-1626179-1628464-,K. Irving - M. Morris - M. Smart - T. Rozier -...,5,4,1,0.800,0.8,1.2,1.8,...,300,259,323,175,154,1,270,256,233,155
238,Lineups,-201143-202330-202681-203935-1626179-,A. Horford - G. Hayward - K. Irving - M. Smart...,6,3,3,0.500,0.7,0.7,1.3,...,328,220,1,147,154,450,1,223,246,128
239,Lineups,-202681-202694-1626179-1627759-1628464-,K. Irving - M. Morris - T. Rozier - J. Brown -...,6,2,4,0.333,0.7,0.5,0.8,...,336,266,381,198,154,1,318,262,309,435
240,Lineups,-203382-203935-1626179-1627759-1628369-,A. Baynes - M. Smart - T. Rozier - J. Brown - ...,4,3,1,0.750,0.6,0.5,0.8,...,290,283,342,198,154,1,244,287,306,375
241,Lineups,-201143-202330-203382-1626179-1628369-,A. Horford - G. Hayward - A. Baynes - T. Rozie...,6,4,2,0.667,0.6,0.7,1.3,...,302,266,1,182,154,1,251,284,303,180
242,Lineups,-201143-202330-202681-202694-1626179-,A. Horford - G. Hayward - K. Irving - M. Morri...,5,5,0,1.000,0.6,0.4,0.8,...,326,288,293,198,154,1,270,256,308,409
243,Lineups,-202330-202681-202694-203935-1628369-,G. Hayward - K. Irving - M. Morris - M. Smart ...,6,3,3,0.500,0.6,0.5,1.2,...,336,290,288,147,154,1,273,206,252,386
244,Lineups,-202681-1626179-1627759-1628369-1628464-,K. Irving - T. Rozier - J. Brown - J. Tatum - ...,6,2,4,0.333,0.6,0.3,0.8,...,234,266,288,182,134,1,239,206,309,174
245,Lineups,-202330-202681-203382-203935-1628369-,G. Hayward - K. Irving - A. Baynes - M. Smart ...,8,4,4,0.500,0.5,0.4,0.9,...,331,263,1,144,154,1,269,261,334,386
246,Lineups,-201143-202330-203935-1627759-1628369-,A. Horford - G. Hayward - M. Smart - J. Brown ...,8,4,4,0.500,0.4,0.4,0.5,...,302,283,296,191,154,1,273,275,311,414
247,Lineups,-202330-202681-203935-1627759-1628464-,G. Hayward - K. Irving - M. Smart - J. Brown -...,10,6,4,0.600,0.4,0.3,0.7,...,333,281,323,175,154,402,240,282,336,399
248,Lineups,-202681-202694-203935-1627759-1628369-,K. Irving - M. Morris - M. Smart - J. Brown - ...,6,1,5,0.167,0.4,0.2,0.5,...,302,290,288,198,154,1,273,284,344,402
249,Lineups,-201143-202681-203935-1628369-1628464-,A. Horford - K. Irving - M. Smart - J. Tatum -...,10,5,5,0.500,0.2,0.2,0.3,...,333,293,283,196,154,1,238,256,312,139

### Available Methods
* lineups()
* overall()

## TeamOpponentSplits
Use: view team performance vs conference, division, and opponent

In [40]:
team.TeamOpponentSplits(bos_id, season = '2018-19').by_conference()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,vs. Conference,East,52,35,17,0.673,48.3,42.3,91.3,0.463,...,1,2,1,2,1,2,1,1,164,East
1,vs. Conference,West,30,14,16,0.467,48.2,41.8,89.1,0.469,...,2,1,2,1,2,1,2,2,164,West

### Available Methods
* by_conference()
* by_division()
* by_opponent()

## TeamPassTracking
Use: Get passing rates by player and associated FG information

In [41]:
team.TeamPassTracking(bos_id, season = '2018-19').passes_made()

,TEAM_ID,TEAM_NAME,PASS_TYPE,G,PASS_FROM,PASS_TEAMMATE_PLAYER_ID,FREQUENCY,PASS,AST,FGM,FGA,FG_PCT,FG2M,FG2A,FG2_PCT,FG3M,FG3A,FG3_PCT
0,1610612738,Boston Celtics,made,67,"Irving, Kyrie",202681,0.141,51.30,6.85,8.18,17.13,0.477,5.58,10.58,0.528,2.60,6.55,0.396
1,1610612738,Boston Celtics,made,68,"Horford, Al",201143,0.120,42.87,4.18,6.16,14.29,0.431,4.07,8.54,0.477,2.09,5.75,0.363
2,1610612738,Boston Celtics,made,79,"Rozier, Terry",1626179,0.131,40.30,2.90,4.29,10.71,0.401,2.78,6.39,0.436,1.51,4.32,0.349
3,1610612738,Boston Celtics,made,80,"Smart, Marcus",203935,0.119,36.18,4.01,5.71,12.50,0.457,3.98,8.21,0.484,1.74,4.29,0.405
4,1610612738,Boston Celtics,made,72,"Hayward, Gordon",202330,0.097,32.75,3.39,4.53,10.56,0.429,2.89,6.29,0.459,1.64,4.26,0.384
5,1610612738,Boston Celtics,made,75,"Morris, Marcus",202694,0.092,29.68,1.45,2.63,6.52,0.403,1.89,4.04,0.469,0.73,2.48,0.296
6,1610612738,Boston Celtics,made,79,"Tatum, Jayson",1628369,0.091,28.16,2.13,3.22,7.61,0.423,2.10,4.42,0.476,1.11,3.19,0.349
7,1610612738,Boston Celtics,made,1,"Hunter, RJ",1626154,0.001,20.00,3.00,3.00,7.00,0.429,1.00,3.00,0.333,2.00,4.00,0.500
8,1610612738,Boston Celtics,made,51,"Baynes, Aron",203382,0.038,17.90,1.10,2.02,5.00,0.404,1.29,3.06,0.423,0.73,1.94,0.374
9,1610612738,Boston Celtics,made,74,"Brown, Jaylen",1627759,0.053,17.47,1.35,1.92,4.59,0.418,1.26,2.72,0.463,0.66,1.88,0.353
10,1610612738,Boston Celtics,made,66,"Theis, Daniel",1628464,0.046,16.89,1.03,1.88,4.35,0.432,1.27,2.70,0.472,0.61,1.65,0.367
11,1610612738,Boston Celtics,made,36,"Wanamaker, Brad",202954,0.023,15.28,1.58,1.94,5.00,0.389,1.44,3.17,0.456,0.50,1.83,0.273
12,1610612738,Boston Celtics,made,5,"Dozier, PJ",1628408,0.003,12.60,1.00,2.00,4.60,0.435,1.20,2.60,0.462,0.80,2.00,0.400
13,1610612738,Boston Celtics,made,56,"Ojeleye, Semi",1628400,0.023,9.84,0.41,0.77,1.82,0.422,0.52,1.21,0.426,0.25,0.61,0.412
14,1610612738,Boston Celtics,made,30,"Williams III, Robert",1629057,0.012,9.73,0.20,0.50,2.10,0.238,0.40,1.27,0.316,0.10,0.83,0.120
15,1610612738,Boston Celtics,made,37,"Yabusele, Guerschon",1627824,0.011,7.46,0.41,0.86,2.05,0.421,0.62,1.41,0.442,0.24,0.65,0.375
16,1610612738,Boston Celtics,made,2,"Monroe, Greg",202328,0.000,2.50,0.50,0.50,0.50,1.000,0.50,0.50,1.000,0.00,0.00,NaN
17,1610612738,Orlando Magic,made,1,"Ross, Terrence",203082,0.000,1.00,0.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,0.00,NaN
18,1610612738,Indiana Pacers,made,1,"Sabonis, Domantas",1627734,0.000,1.00,0.00,0.00,0.00,NaN,0.00,0.00,NaN,0.00,0.00,NaN

### Available Methods
* passes_made()
* passes_received()

## TeamPerformanceSplits
Use: team performance by scoring splits

In [42]:
team.TeamPerformanceSplits(bos_id, season = '2018-19').points_against()

,GROUP_SET,GROUP_VALUE_ORDER,GROUP_VALUE,GROUP_VALUE_2,GP,W,L,W_PCT,MIN,FGM,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Points Against,NaN,W,70-79 Points,1,1,0,1.0,48.0,50.0,...,1,2,6,1,1,5,1,1,189,None
1,Points Against,NaN,W,80-89 Points,3,3,0,1.0,48.0,41.0,...,5,6,1,5,3,2,4,2,190,None
2,Points Against,NaN,W,90-99 Points,12,12,0,1.0,48.0,44.3,...,3,1,3,4,5,4,3,3,191,None
3,Points Against,NaN,W,100+ Points,33,33,0,1.0,48.6,43.7,...,5,3,4,3,6,1,2,4,192,None
4,Points Against,0.0,W,All,49,49,0,1.0,48.4,43.8,...,2,1,2,1,2,1,1,1,186,None
5,Points Against,NaN,L,90-99 Points,4,0,4,0.0,48.0,37.8,...,3,4,5,2,2,6,6,5,196,None
6,Points Against,NaN,L,100+ Points,29,0,29,0.0,48.0,39.8,...,2,5,2,6,4,3,5,6,197,None
7,Points Against,0.0,L,All,33,0,33,0.0,48.0,39.5,...,1,2,1,2,1,2,2,2,193,None

### Available Methods
* points_against()
* points_scored()
* score_differential()

## TeamPlayerOnOffDetail
Use: Team performance with player on/off the court

In [43]:
team.TeamPlayerOnOffDetail(bos_id, season= '2018-19').off_court()

,GROUP_SET,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,VS_PLAYER_ID,VS_PLAYER_NAME,COURT_STATUS,GP,W,L,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,On/Off Court,1610612738,BOS,Boston Celtics,203382,"Baynes, Aron",Off,82,49,33,...,11,11,11,11,10,12,10,11,11,11
1,On/Off Court,1610612738,BOS,Boston Celtics,1628444,"Bird, Jabari",Off,55,35,20,...,3,2,19,2,1,19,19,2,2,1
2,On/Off Court,1610612738,BOS,Boston Celtics,1627759,"Brown, Jaylen",Off,82,49,33,...,15,14,6,16,16,6,5,15,14,7
3,On/Off Court,1610612738,BOS,Boston Celtics,1628408,"Dozier, PJ",Off,82,49,33,...,4,3,18,3,3,17,18,3,3,6
4,On/Off Court,1610612738,BOS,Boston Celtics,1626780,"Gibson, Jonathan",Off,1,1,0,...,1,1,5,1,12,11,11,6,1,2
5,On/Off Court,1610612738,BOS,Boston Celtics,202330,"Hayward, Gordon",Off,82,49,33,...,14,15,8,14,13,7,6,16,15,15
6,On/Off Court,1610612738,BOS,Boston Celtics,201143,"Horford, Al",Off,82,49,33,...,16,17,7,15,17,8,7,13,16,16
7,On/Off Court,1610612738,BOS,Boston Celtics,1626154,"Hunter, RJ",Off,42,24,18,...,6,4,17,5,4,18,17,4,4,17
8,On/Off Court,1610612738,BOS,Boston Celtics,202681,"Irving, Kyrie",Off,82,49,33,...,19,19,2,18,18,2,2,19,19,18
9,On/Off Court,1610612738,BOS,Boston Celtics,1627215,"Lemon Jr., Walter",Off,21,11,10,...,2,7,20,4,2,20,20,1,5,13
10,On/Off Court,1610612738,BOS,Boston Celtics,202328,"Monroe, Greg",Off,5,3,2,...,5,9,14,10,11,9,16,9,8,20
11,On/Off Court,1610612738,BOS,Boston Celtics,202694,"Morris, Marcus",Off,82,49,33,...,17,16,4,17,14,4,4,17,17,10
12,On/Off Court,1610612738,BOS,Boston Celtics,1628400,"Ojeleye, Semi",Off,82,49,33,...,10,10,12,9,8,13,12,10,10,8
13,On/Off Court,1610612738,BOS,Boston Celtics,1626179,"Rozier, Terry",Off,82,49,33,...,13,13,9,13,15,3,8,14,13,4
14,On/Off Court,1610612738,BOS,Boston Celtics,203935,"Smart, Marcus",Off,82,49,33,...,18,18,3,19,19,5,3,18,18,14
15,On/Off Court,1610612738,BOS,Boston Celtics,1628369,"Tatum, Jayson",Off,82,49,33,...,20,20,1,20,20,1,1,20,20,19
16,On/Off Court,1610612738,BOS,Boston Celtics,1628464,"Theis, Daniel",Off,82,49,33,...,12,12,10,12,9,10,9,12,12,12
17,On/Off Court,1610612738,BOS,Boston Celtics,202954,"Wanamaker, Brad",Off,82,49,33,...,9,8,13,8,6,15,13,8,9,9
18,On/Off Court,1610612738,BOS,Boston Celtics,1629057,"Williams III, Robert",Off,82,49,33,...,8,6,15,7,7,15,15,7,7,3
19,On/Off Court,1610612738,BOS,Boston Celtics,1627824,"Yabusele, Guerschon",Off,82,49,33,...,7,5,16,6,5,14,14,5,6,5

### Available Methods
* off_court()
* on_court()

## TeamPlayerOnOffSummary
Use: Team performance with player on/off the court

In [44]:
team.TeamPlayerOnOffSummary(bos_id, season= '2018-19').on_court()

,GROUP_SET,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,VS_PLAYER_ID,VS_PLAYER_NAME,COURT_STATUS,GP,MIN,PLUS_MINUS,OFF_RATING,DEF_RATING,NET_RATING
0,On/Off Court,1610612738,BOS,Boston Celtics,203382,"Baynes, Aron",On,51,821.0,7.6,110.0,102.2,7.7
1,On/Off Court,1610612738,BOS,Boston Celtics,1627759,"Brown, Jaylen",On,74,1913.0,1.6,108.3,106.0,2.3
2,On/Off Court,1610612738,BOS,Boston Celtics,1628408,"Dozier, PJ",On,6,51.0,23.6,112.6,90.1,22.5
3,On/Off Court,1610612738,BOS,Boston Celtics,202330,"Hayward, Gordon",On,72,1863.0,5.5,110.4,105.2,5.2
4,On/Off Court,1610612738,BOS,Boston Celtics,201143,"Horford, Al",On,68,1972.0,6.3,112.5,106.4,6.1
5,On/Off Court,1610612738,BOS,Boston Celtics,1626154,"Hunter, RJ",On,1,26.0,52.3,132.1,79.2,52.8
6,On/Off Court,1610612738,BOS,Boston Celtics,202681,"Irving, Kyrie",On,67,2214.0,7.2,113.4,107.1,6.2
7,On/Off Court,1610612738,BOS,Boston Celtics,202328,"Monroe, Greg",On,2,5.0,49.8,155.6,100.0,55.6
8,On/Off Court,1610612738,BOS,Boston Celtics,202694,"Morris, Marcus",On,75,2090.0,1.7,110.3,108.9,1.4
9,On/Off Court,1610612738,BOS,Boston Celtics,1628400,"Ojeleye, Semi",On,56,594.0,5.7,106.3,100.2,6.0
10,On/Off Court,1610612738,BOS,Boston Celtics,1626179,"Rozier, Terry",On,79,1791.0,-1.0,104.9,105.9,-1.1
11,On/Off Court,1610612738,BOS,Boston Celtics,203935,"Smart, Marcus",On,80,2200.0,3.6,110.4,106.6,3.8
12,On/Off Court,1610612738,BOS,Boston Celtics,1628369,"Tatum, Jayson",On,79,2454.0,7.0,112.0,105.1,6.9
13,On/Off Court,1610612738,BOS,Boston Celtics,1628464,"Theis, Daniel",On,66,908.0,6.9,110.0,102.6,7.4
14,On/Off Court,1610612738,BOS,Boston Celtics,202954,"Wanamaker, Brad",On,36,343.0,10.1,106.6,97.8,8.8
15,On/Off Court,1610612738,BOS,Boston Celtics,1629057,"Williams III, Robert",On,32,283.0,-8.5,98.2,104.1,-5.9
16,On/Off Court,1610612738,BOS,Boston Celtics,1627824,"Yabusele, Guerschon",On,41,251.0,-3.4,102.4,106.0,-3.6

### Available Methods
* off_court()
* on_court()

## TeamPlayers
Use: player season stats and in team ranking

In [45]:
team.TeamPlayers(bos_id, season= '2018-19').season_totals()

,GROUP_SET,PLAYER_ID,PLAYER_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,...,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK
0,Players,201143,Al Horford,68,41,27,0.603,29.0,5.7,10.6,...,6,1,7,9,8,5,5,2,2,1
1,Players,203382,Aron Baynes,51,32,19,0.627,16.1,2.1,4.4,...,14,4,10,5,7,11,7,10,5,3
2,Players,202954,Brad Wanamaker,36,27,9,0.750,9.5,1.4,2.9,...,10,14,16,13,12,12,10,14,12,3
3,Players,1628464,Daniel Theis,66,38,28,0.576,13.8,2.2,4.0,...,12,5,11,6,10,10,11,11,8,3
4,Players,202330,Gordon Hayward,72,44,28,0.611,25.9,4.1,8.8,...,7,10,8,10,3,7,6,6,6,3
5,Players,202328,Greg Monroe,2,0,2,0.000,2.4,1.5,2.5,...,17,15,5,17,17,15,8,16,12,3
6,Players,1627824,Guerschon Yabusele,41,27,14,0.659,6.1,0.9,1.9,...,15,12,15,14,15,17,15,17,12,3
7,Players,1627759,Jaylen Brown,74,41,33,0.554,25.9,5.0,10.7,...,5,7,4,2,4,6,14,8,6,3
8,Players,1628369,Jayson Tatum,79,48,31,0.608,31.1,5.9,13.1,...,3,3,3,8,2,3,3,3,3,3
9,Players,202681,Kyrie Irving,67,37,30,0.552,33.0,9.0,18.5,...,2,6,2,4,1,1,2,1,1,1
10,Players,202694,Marcus Morris,75,44,31,0.587,27.9,5.0,11.3,...,9,9,6,7,5,4,13,5,4,3
11,Players,203935,Marcus Smart,80,48,32,0.600,27.5,3.0,7.1,...,1,8,13,3,6,9,9,7,8,3
12,Players,1628408,PJ Dozier,6,5,1,0.833,8.5,1.3,3.5,...,10,15,17,16,14,14,4,13,8,3
13,Players,1626154,RJ Hunter,1,1,0,1.000,25.7,6.0,13.0,...,4,15,1,1,11,2,1,4,12,3
14,Players,1629057,Robert Williams III,32,18,14,0.563,8.8,1.1,1.6,...,13,2,14,12,16,16,17,12,12,3
15,Players,1628400,Semi Ojeleye,56,39,17,0.696,10.6,1.2,2.8,...,16,13,12,15,13,13,12,15,12,3
16,Players,1626179,Terry Rozier,79,47,32,0.595,22.7,3.3,8.4,...,8,11,9,11,9,8,16,9,8,3

### Available Methods
* season_totals()

## TeamReboundTracking
Use: Segmented eam rebounding statistics

In [46]:
team.TeamReboundTracking(bos_id, season= '2018-19').contested_rebounding()

,TEAM_ID,TEAM_NAME,SORT_ORDER,G,REB_NUM_CONTESTING_RANGE,REB_FREQUENCY,OREB,DREB,REB,C_OREB,C_DREB,C_REB,C_REB_PCT,UC_OREB,UC_DREB,UC_REB,UC_REB_PCT
0,1610612738,Boston Celtics,1,82,0 Contesting Rebounders,0.713,4.45,27.27,31.72,0.00,0.00,0.00,0.0,4.45,27.27,31.72,1.0
1,1610612738,Boston Celtics,2,82,1 Contesting Rebounder,0.255,4.18,7.16,11.34,4.18,7.16,11.34,1.0,0.00,0.00,0.00,0.0
2,1610612738,Boston Celtics,3,82,2+ Contesting Rebounders,0.032,1.15,0.29,1.44,1.15,0.29,1.44,1.0,0.00,0.00,0.00,0.0

### Available Methods
* contested_rebounding()
* rebound_distance_rebounding()
* shot_distance_rebounding()
* shot_type_rebounding()

## TeamSeasons
Use: Team performance season by season

In [48]:
team.TeamSeasons(bos_id).info()

,TEAM_ID,TEAM_CITY,TEAM_NAME,YEAR,GP,WINS,LOSSES,WIN_PCT,CONF_RANK,DIV_RANK,...,OREB,DREB,REB,AST,PF,STL,TOV,BLK,PTS,PTS_RANK
0,1610612738,Boston,Celtics,1946-47,60,22,38,0.367,0,5,...,0.0,0.0,0.0,7.8,20.0,0.0,0.0,0.0,60.1,11
1,1610612738,Boston,Celtics,1947-48,48,20,28,0.417,0,3,...,0.0,0.0,0.0,7.6,22.2,0.0,0.0,0.0,68.8,8
2,1610612738,Boston,Celtics,1948-49,60,25,35,0.417,0,5,...,0.0,0.0,0.0,18.9,23.0,0.0,0.0,0.0,76.6,9
3,1610612738,Boston,Celtics,1949-50,68,22,46,0.324,0,6,...,0.0,0.0,0.0,21.7,24.2,0.0,0.0,0.0,79.7,9
4,1610612738,Boston,Celtics,1950-51,69,39,30,0.565,0,2,...,0.0,0.0,0.0,22.9,27.3,0.0,0.0,0.0,85.2,4
5,1610612738,Boston,Celtics,1951-52,66,39,27,0.591,0,2,...,0.0,0.0,0.0,24.3,26.3,0.0,0.0,0.0,91.3,1
6,1610612738,Boston,Celtics,1952-53,71,46,25,0.648,0,3,...,0.0,0.0,0.0,23.5,26.9,0.0,0.0,0.0,88.1,1
7,1610612738,Boston,Celtics,1953-54,72,42,30,0.583,0,2,...,0.0,0.0,0.0,24.6,27.3,0.0,0.0,0.0,87.7,1
8,1610612738,Boston,Celtics,1954-55,72,36,36,0.500,0,3,...,0.0,0.0,0.0,26.5,25.8,0.0,0.0,0.0,101.5,1
9,1610612738,Boston,Celtics,1955-56,72,39,33,0.542,0,2,...,0.0,0.0,0.0,25.5,26.0,0.0,0.0,0.0,106.0,1
10,1610612738,Boston,Celtics,1956-57,72,44,28,0.611,0,1,...,0.0,0.0,0.0,20.3,25.7,0.0,0.0,0.0,105.5,1
11,1610612738,Boston,Celtics,1957-58,72,49,23,0.681,0,1,...,0.0,0.0,0.0,20.9,23.9,0.0,0.0,0.0,109.9,2
12,1610612738,Boston,Celtics,1958-59,72,52,20,0.722,0,1,...,0.0,0.0,0.0,21.8,24.6,0.0,0.0,0.0,116.4,1
13,1610612738,Boston,Celtics,1959-60,75,59,16,0.787,0,1,...,0.0,0.0,0.0,24.7,24.7,0.0,0.0,0.0,124.5,1
14,1610612738,Boston,Celtics,1960-61,79,57,22,0.722,0,1,...,0.0,0.0,0.0,23.7,25.7,0.0,0.0,0.0,119.7,3
15,1610612738,Boston,Celtics,1961-62,80,60,20,0.750,0,1,...,0.0,0.0,0.0,25.6,23.9,0.0,0.0,0.0,121.1,3
16,1610612738,Boston,Celtics,1962-63,80,58,22,0.725,0,1,...,0.0,0.0,0.0,24.5,26.1,0.0,0.0,0.0,118.8,3
17,1610612738,Boston,Celtics,1963-64,80,59,21,0.738,0,1,...,0.0,0.0,0.0,22.0,26.6,0.0,0.0,0.0,113.0,2
18,1610612738,Boston,Celtics,1964-65,80,62,18,0.775,0,1,...,0.0,0.0,0.0,22.2,25.8,0.0,0.0,0.0,112.8,3
19,1610612738,Boston,Celtics,1965-66,80,54,26,0.675,0,2,...,0.0,0.0,0.0,22.4,25.2,0.0,0.0,0.0,112.7,7
20,1610612738,Boston,Celtics,1966-67,81,60,21,0.741,0,2,...,0.0,0.0,0.0,24.2,26.4,0.0,0.0,0.0,119.3,4
21,1610612738,Boston,Celtics,1967-68,82,54,28,0.659,0,2,...,0.0,0.0,0.0,21.9,26.2,0.0,0.0,0.0,116.1,8
22,1610612738,Boston,Celtics,1968-69,82,48,34,0.585,0,4,...,0.0,0.0,0.0,23.8,25.3,0.0,0.0,0.0,111.0,10
23,1610612738,Boston,Celtics,1969-70,82,34,48,0.415,0,6,...,0.0,0.0,0.0,22.9,28.3,0.0,0.0,0.0,114.9,11
24,1610612738,Boston,Celtics,1970-71,82,44,38,0.537,5,3,...,0.0,0.0,0.0,25.0,26.1,0.0,0.0,0.0,117.2,2
25,1610612738,Boston,Celtics,1971-72,82,56,26,0.683,1,1,...,0.0,0.0,0.0,27.2,24.8,0.0,0.0,0.0,115.6,3
26,1610612738,Boston,Celtics,1972-73,82,68,14,0.829,1,1,...,0.0,0.0,0.0,28.3,22.0,0.0,0.0,0.0,112.7,2
27,1610612738,Boston,Celtics,1973-74,82,56,26,0.683,1,1,...,16.8,37.5,54.3,26.7,22.8,6.8,21.9,3.7,109.0,4
28,1610612738,Boston,Celtics,1974-75,82,60,22,0.732,1,1,...,16.0,36.0,52.0,26.3,23.3,8.1,19.8,3.5,106.5,3
29,1610612738,Boston,Celtics,1975-76,82,54,28,0.659,1,1,...,16.7,36.2,52.9,24.1,24.4,6.8,19.6,3.2,106.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,1610612738,Boston,Celtics,1989-90,82,52,30,0.634,4,2,...,13.0,33.0,46.0,29.5,20.9,6.6,15.3,5.5,110.0,8
44,1610612738,Boston,Celtics,1990-91,82,56,26,0.683,2,1,...,13.3,32.9,46.2,26.3,20.7,8.2,16.1,6.9,111.5,6
45,1610612738,Boston,Celtics,1991-92,82,51,31,0.622,2,1,...,13.4,31.5,44.9,25.3,20.6,7.8,14.2,5.9,106.6,9
46,1610612738,Boston,Celtics,1992-93,82,48,34,0.585,4,2,...,13.1,29.7,42.8,24.4,22.7,7.9,14.3,5.6,103.7,19
47,1610612738,Boston,Celtics,1993-94,82,32,50,0.390,10,5,...,12.6,29.0,41.7,23.5,22.5,8.2,15.1,5.4,100.8,16
48,1610612738,Boston,Celtics,1994-95,82,35,47,0.427,8,3,...,14.1,28.3,42.4,21.7,24.1,7.5,15.9,4.4,102.8,11
49,1610612738,Boston,Celtics,1995-96,82,33,49,0.402,11,5,...,12.8,29.6,42.4,21.9,24.9,8.0,15.9,5.0,103.6,5
50,1610612738,Boston,Celtics,1996-97,82,15,67,0.183,15,7,...,13.4,26.7,40.0,21.9,23.4,9.9,16.4,3.8,100.6,5
51,1610612738,Boston,Celtics,1997-98,82,36,46,0.439,12,6,...,14.6,24.9,39.5,22.1,26.9,12.0,16.2,4.5,95.9,14
52,1610612738,Boston,Celtics,1998-99,50,19,31,0.380,12,5,...,13.6,29.2,42.8,21.5,23.9,9.1,16.1,5.1,93.0,10
53,1610612738,Boston,Celtics,1999-00,82,35,47,0.427,10,5,...,13.5,29.5,43.0,21.2,27.1,9.7,15.4,3.5,99.3,9
54,1610612738,Boston,Celtics,2000-01,82,36,46,0.439,9,5,...,10.9,28.9,39.8,20.8,23.8,9.4,15.7,4.1,94.6,16
55,1610612738,Boston,Celtics,2001-02,82,49,33,0.598,3,2,...,10.9,31.3,42.2,21.0,21.7,9.7,13.6,3.6,96.4,12
56,1610612738,Boston,Celtics,2002-03,82,44,38,0.537,6,3,...,10.4,30.1,40.5,19.2,21.4,8.8,14.0,3.7,92.7,22
57,1610612738,Boston,Celtics,2003-04,82,36,46,0.439,8,4,...,10.4,29.8,40.1,20.5,22.4,9.4,16.2,4.0,95.3,8
58,1610612738,Boston,Celtics,2004-05,82,45,37,0.549,4,1,...,11.1,29.7,40.8,22.1,24.4,8.1,15.8,5.2,101.3,5
59,1610612738,Boston,Celtics,2005-06,82,33,49,0.402,11,3,...,9.9,29.7,39.6,20.9,24.8,7.0,16.6,5.1,98.0,12
60,1610612738,Boston,Celtics,2006-07,82,24,58,0.293,15,5,...,11.2,29.2,40.4,19.9,24.0,7.2,16.5,4.7,95.8,22
61,1610612738,Boston,Celtics,2007-08,82,66,16,0.805,1,1,...,10.1,31.9,42.0,22.4,22.7,8.5,15.2,4.6,100.5,11
62,1610612738,Boston,Celtics,2008-09,82,62,20,0.756,2,1,...,10.6,31.5,42.1,22.7,23.1,7.6,15.6,4.7,100.9,11
63,1610612738,Boston,Celtics,2009-10,82,50,32,0.610,4,1,...,8.7,29.9,38.6,23.5,22.1,8.5,14.9,4.9,99.2,19
64,1610612738,Boston,Celtics,2010-11,82,56,26,0.683,3,1,...,7.8,31.0,38.8,23.4,20.5,8.2,14.6,4.2,96.5,23
65,1610612738,Boston,Celtics,2011-12,66,39,27,0.591,4,1,...,7.7,31.1,38.8,23.6,19.9,7.5,14.8,5.5,91.8,26
66,1610612738,Boston,Celtics,2012-13,81,41,40,0.506,7,3,...,8.1,31.3,39.3,22.8,21.2,8.2,14.6,4.5,96.5,18
67,1610612738,Boston,Celtics,2013-14,82,25,57,0.305,12,4,...,12.0,30.5,42.5,21.0,21.3,7.1,15.4,4.2,96.2,26
68,1610612738,Boston,Celtics,2014-15,82,40,42,0.488,7,2,...,11.1,32.7,43.8,24.5,21.2,8.2,13.8,3.6,101.4,13
69,1610612738,Boston,Celtics,2015-16,82,48,34,0.585,5,2,...,11.6,33.3,44.9,24.2,21.9,9.2,13.7,4.2,105.7,5
70,1610612738,Boston,Celtics,2016-17,82,53,29,0.646,1,1,...,9.1,32.9,42.0,25.2,20.6,7.5,13.3,4.1,108.0,7
71,1610612738,Boston,Celtics,2017-18,82,55,27,0.671,2,2,...,9.4,35.1,44.5,22.5,19.7,7.4,14.0,4.5,104.0,20
72,1610612738,Boston,Celtics,2018-19,82,49,33,0.598,4,3,...,9.8,34.7,44.5,26.3,20.4,8.6,12.8,5.3,112.4,14

### Available Methods
* info()

## TeamShootingSplits
Use: Team shooting stats segmented by shot area, type, etc

In [50]:
team.TeamShootingSplits(bos_id, season= '2018-19').assissted_by()

,GROUP_SET,PLAYER_ID,PLAYER_NAME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,EFG_PCT,...,EFG_PCT_RANK,BLKA_RANK,PCT_AST_2PM_RANK,PCT_UAST_2PM_RANK,PCT_AST_3PM_RANK,PCT_UAST_3PM_RANK,PCT_AST_FGM_RANK,PCT_UAST_FGM_RANK,CFID,CFPARAMS
0,Assisted By,203382,"Baynes, Aron",57,57,1.0,30,30,1.0,1.263,...,3,1,1,1,1,1,1,1,168,203382
1,Assisted By,1627759,"Brown, Jaylen",100,100,1.0,43,43,1.0,1.215,...,9,1,1,1,1,1,1,1,168,1627759
2,Assisted By,1628408,"Dozier, PJ",5,5,1.0,1,1,1.0,1.100,...,15,1,1,1,1,1,1,1,168,1628408
3,Assisted By,202330,"Hayward, Gordon",244,244,1.0,104,104,1.0,1.213,...,10,1,1,1,1,1,1,1,168,202330
4,Assisted By,201143,"Horford, Al",283,283,1.0,123,123,1.0,1.217,...,8,1,1,1,1,1,1,1,168,201143
5,Assisted By,1626154,"Hunter, RJ",3,3,1.0,2,2,1.0,1.333,...,1,1,1,1,1,1,1,1,168,1626154
6,Assisted By,202681,"Irving, Kyrie",464,464,1.0,165,165,1.0,1.178,...,13,1,1,1,1,1,1,1,168,202681
7,Assisted By,202328,"Monroe, Greg",1,1,1.0,0,0,0.0,1.000,...,17,1,1,1,17,1,1,1,168,202328
8,Assisted By,202694,"Morris, Marcus",109,109,1.0,41,41,1.0,1.188,...,12,1,1,1,1,1,1,1,168,202694
9,Assisted By,1628400,"Ojeleye, Semi",23,23,1.0,12,12,1.0,1.261,...,4,1,1,1,1,1,1,1,168,1628400
10,Assisted By,1626179,"Rozier, Terry",231,231,1.0,107,107,1.0,1.232,...,5,1,1,1,1,1,1,1,168,1626179
11,Assisted By,203935,"Smart, Marcus",321,321,1.0,121,121,1.0,1.188,...,11,1,1,1,1,1,1,1,168,203935
12,Assisted By,1628369,"Tatum, Jayson",168,168,1.0,76,76,1.0,1.226,...,6,1,1,1,1,1,1,1,168,1628369
13,Assisted By,1628464,"Theis, Daniel",68,68,1.0,30,30,1.0,1.221,...,7,1,1,1,1,1,1,1,168,1628464
14,Assisted By,202954,"Wanamaker, Brad",56,56,1.0,17,17,1.0,1.152,...,14,1,1,1,1,1,1,1,168,202954
15,Assisted By,1629057,"Williams III, Robert",7,7,1.0,1,1,1.0,1.071,...,16,1,1,1,1,1,1,1,168,1629057
16,Assisted By,1627824,"Yabusele, Guerschon",15,15,1.0,8,8,1.0,1.267,...,2,1,1,1,1,1,1,1,168,1627824

### Available Methods
* assissted_by() -note the spelling error in the method
* assisted_shots()
* shot_5ft()
* shot_8ft()
* shot_areas()
* shot_type_summary()

## TeamShotTracking
Use: Team shooting performance segmented by defense, time, and type

In [51]:
team.TeamShotTracking(bos_id, season= '2018-19').closest_defender_shooting()

,TEAM_ID,TEAM_NAME,SORT_ORDER,G,CLOSE_DEF_DIST_RANGE,FGA_FREQUENCY,FGM,FGA,FG_PCT,EFG_PCT,FG2A_FREQUENCY,FG2M,FG2A,FG2_PCT,FG3A_FREQUENCY,FG3M,FG3A,FG3_PCT
0,1610612738,Boston Celtics,1,82,0-2 Feet - Very Tight,0.102,4.39,9.23,0.476,0.482,0.098,4.28,8.87,0.483,0.004,0.11,0.37,0.300
1,1610612738,Boston Celtics,2,82,2-4 Feet - Tight,0.333,15.35,30.16,0.509,0.527,0.298,14.29,26.95,0.530,0.035,1.06,3.21,0.331
2,1610612738,Boston Celtics,3,82,4-6 Feet - Open,0.295,11.76,26.74,0.440,0.520,0.161,7.48,14.60,0.512,0.134,4.28,12.15,0.352
3,1610612738,Boston Celtics,4,82,6+ Feet - Wide Open,0.270,10.59,24.41,0.434,0.580,0.062,3.45,5.63,0.613,0.207,7.13,18.78,0.380

### Available Methods
* closest_defender_shooting()
* closest_defender_shooting_long()
* dribble_shooting()
* shot_clock_shooting()
* touch_time_shooting()

## TeamSummary
Use: Basic team level information and rankings

In [52]:
team.TeamSummary(bos_id, season= '2018-19').info()

,TEAM_ID,SEASON_YEAR,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CONFERENCE,TEAM_DIVISION,TEAM_CODE,W,L,PCT,CONF_RANK,DIV_RANK,MIN_YEAR,MAX_YEAR
0,1610612738,2018-19,Boston,Celtics,BOS,East,Atlantic,celtics,49,33,0.598,4,3,1946,2019

### Available Methods
* info()
* season_ranks()

## TeamVsPlayer
Use: Team performance against a team/player

In [61]:
atl_id = 1610612737
atl_roster = team.TeamCommonRoster(atl_id, season= '2018-19').roster()
trae_id = atl_roster[atl_roster.PLAYER == "Trae Young"]['PLAYER_ID']

In [63]:
team.TeamVsPlayer(bos_id, trae_id, season= '2018-19').on_off_court()

,GROUP_SET,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,VS_PLAYER_ID,VS_PLAYER_NAME,COURT_STATUS,GP,W,L,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,Vs. Player,1610612738,BOS,Boston Celtics,1629027,"Young, Trae",On,4,4,0,...,1,1,1,2,1,1,1,1,214,1629027
1,Vs. Player,1610612738,BOS,Boston Celtics,1629027,"Young, Trae",Off,4,4,0,...,2,2,2,1,2,2,2,2,215,1629027

### Available Methods
* on_off_court()
* overall()
* shot_area_off_court()
* shot_area_on_court()
* shot_area_overall()
* shot_distance_off_court()
* shot_distance_on_court()
* shot_distance_overall()
* vs_player_overall()

## TeamYearOverYearSplits
Use: Team stats year over year

In [64]:
team.TeamYearOverYearSplits(bos_id).by_year()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,By Year,2018-19,82,49,33,0.598,48.2,42.1,90.5,0.465,...,1,10,2,1,3,9,1,4,210,2018-19
1,By Year,2017-18,82,55,27,0.671,48.3,38.3,85.1,0.450,...,7,20,10,2,1,11,4,6,210,2017-18
2,By Year,2016-17,82,53,29,0.646,48.2,38.6,85.1,0.454,...,2,19,16,16,5,7,2,8,210,2016-17
3,By Year,2015-16,82,48,34,0.585,48.2,39.2,89.2,0.439,...,4,7,13,20,11,6,3,7,210,2015-16
4,By Year,2014-15,82,40,42,0.488,48.5,38.9,87.9,0.443,...,5,15,21,17,6,13,5,12,210,2014-15
5,By Year,2013-14,82,25,57,0.305,48.1,36.5,83.9,0.435,...,14,22,15,5,8,12,16,22,210,2013-14
6,By Year,2012-13,81,41,40,0.506,49.0,37.0,79.7,0.465,...,9,14,11,7,7,10,13,13,210,2012-13
7,By Year,2011-12,66,39,27,0.591,48.3,35.5,77.1,0.460,...,10,18,1,6,2,14,23,9,210,2011-12
8,By Year,2010-11,82,56,26,0.683,48.2,36.9,75.8,0.486,...,8,13,14,2,4,8,14,3,210,2010-11
9,By Year,2009-10,82,50,32,0.610,48.2,37.1,76.8,0.483,...,11,11,6,8,12,4,11,5,210,2009-10
10,By Year,2008-09,82,62,20,0.756,48.5,37.5,77.2,0.486,...,15,17,7,9,15,2,7,2,210,2008-09
11,By Year,2007-08,82,66,16,0.805,48.2,36.4,76.7,0.475,...,12,12,9,9,14,3,9,1,210,2007-08
12,By Year,2006-07,82,24,58,0.293,48.4,34.9,78.7,0.443,...,22,21,8,19,19,5,18,21,210,2006-07
13,By Year,2005-06,82,33,49,0.402,48.5,36.0,77.1,0.467,...,23,23,4,12,21,1,12,17,210,2005-06
14,By Year,2004-05,82,45,37,0.549,48.5,37.1,79.4,0.468,...,17,16,3,11,20,20,6,11,210,2004-05
15,By Year,2003-04,82,36,46,0.439,48.1,34.7,78.2,0.443,...,20,5,18,14,13,23,19,16,210,2003-04
16,By Year,2002-03,82,44,38,0.537,48.4,32.9,79.4,0.415,...,6,9,20,4,9,19,22,14,210,2002-03
17,By Year,2001-02,82,49,33,0.598,48.4,34.8,82.1,0.424,...,3,4,22,22,10,20,15,10,210,2001-02
18,By Year,2000-01,82,36,46,0.439,48.4,33.8,79.1,0.428,...,16,6,17,18,17,20,20,19,210,2000-01
19,By Year,1999-00,82,35,47,0.427,48.1,37.2,83.9,0.444,...,13,3,23,21,23,15,10,15,210,1999-00
20,By Year,1998-99,50,19,31,0.380,48.6,36.3,83.3,0.436,...,18,8,5,15,18,17,21,18,210,1998-99
21,By Year,1997-98,82,36,46,0.439,48.1,36.7,84.6,0.434,...,19,1,12,13,22,16,17,20,210,1997-98
22,By Year,1996-97,82,15,67,0.183,48.5,37.4,85.0,0.440,...,21,2,19,23,16,18,8,23,210,1996-97

### Available Methods
* by_year()

# Player Module

## PlayerCareer
Uses: player stats for preseason, regular, postseason, and college

In [66]:
player.PlayerCareer(trae_id, per_mode= 'PerGame').regular_season_totals()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1629027,2018-19,00,1610612737,ATL,20.0,81,81,30.9,6.5,...,0.829,0.8,2.9,3.7,8.1,0.9,0.2,3.8,1.7,19.1

### Available Methods
* all_star_season_totals()
* career_all_star_season_totals()
* college_season_career_totals()
* college_season-totals()
* post_season_career_totals()
* post_season_career_totals()
* post_season_rankings()
* post_season_totals()
* preseason_career_totals()
* preseason_season_totals()
* regular_season_career_totals()
* regular_season_rankings()
* regular_season_totals()

## PlayerClutchSplits
Uses: Player stats in clutch situations

In [67]:
player.PlayerClutchSplits(trae_id, season = '2018-19').last10sec_deficit_3point()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Last 10 SEC <= 3 PTS,2018-19,11,4,7,0.364,0.3,0.5,0.6,0.714,...,1,1,1,1,1,1,1,1,13,2018-19

### Available Methods
* last10sec_deficiit_3point()
* last1min_deficit_5point()
* last1min_plusminus_5point()
* last30sec_deficit_3point()
* last30secon_plusminus_5point()
* last3min_deficit_5point()
* last3min_plusminus_5point()
* last5min_eficit_5point()
* last5min_plusminus_5point()

## PlayerDefenseTracking
Uses: Player defensive stats segemented by shot type and distance

In [70]:
player.PlayerDefenseTracking(trae_id, season= '2018-19').overall()

,CLOSE_DEF_PERSON_ID,GP,G,DEFENSE_CATEGORY,FREQ,D_FGM,D_FGA,D_FG_PCT,NORMAL_FG_PCT,PCT_PLUSMINUS
0,1629027,81,81,Overall,1.000,4.69,9.73,0.482,0.441,0.041
1,1629027,81,80,3 Pointers,0.463,1.57,4.51,0.348,0.354,-0.006
2,1629027,81,81,2 Pointers,0.537,3.12,5.22,0.598,0.500,0.098
3,1629027,81,69,Less Than 6 Ft,0.223,1.72,2.17,0.790,0.618,0.172
4,1629027,81,78,Less Than 10 Ft,0.305,2.01,2.96,0.679,0.556,0.123
5,1629027,81,80,Greater Than 15 Ft,0.612,2.32,5.95,0.390,0.370,0.020

### Available Methods
* overall()

## PlayerGameLogs
Uses: player stats by game

In [79]:
player.PlayerGameLogs(trae_id, season= '2018-19').info()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22018,1629027,0021801220,"APR 10, 2019",ATL vs. IND,L,34,6,18,0.333,...,3,5,11,2,0,6,0,23,18,1
1,22018,1629027,0021801181,"APR 05, 2019",ATL @ ORL,L,27,8,17,0.471,...,5,7,6,3,0,2,2,22,-36,1
2,22018,1629027,0021801168,"APR 03, 2019",ATL vs. PHI,W,33,12,18,0.667,...,5,7,12,1,0,2,4,33,6,1
3,22018,1629027,0021801162,"APR 02, 2019",ATL @ SAS,L,30,5,15,0.333,...,1,1,6,1,0,0,3,15,-11,1
4,22018,1629027,0021801145,"MAR 31, 2019",ATL vs. MIL,W,35,5,19,0.263,...,4,5,16,2,0,1,2,12,-5,1
5,22018,1629027,0021801131,"MAR 29, 2019",ATL vs. POR,L,32,10,25,0.400,...,7,9,7,1,0,3,1,26,-5,1
6,22018,1629027,0021801113,"MAR 26, 2019",ATL @ NOP,W,31,12,24,0.500,...,1,1,12,1,0,1,1,33,10,1
7,22018,1629027,0021801088,"MAR 23, 2019",ATL vs. PHI,W,33,11,20,0.550,...,4,6,11,0,1,6,4,32,22,1
8,22018,1629027,0021801076,"MAR 21, 2019",ATL vs. UTA,W,34,8,22,0.364,...,2,2,11,0,0,5,0,23,5,1
9,22018,1629027,0021801060,"MAR 19, 2019",ATL vs. HOU,L,34,6,13,0.462,...,2,4,12,1,0,7,2,21,-12,1
10,22018,1629027,0021801046,"MAR 17, 2019",ATL @ ORL,L,32,9,18,0.500,...,6,6,5,1,0,2,3,20,-18,2
11,22018,1629027,0021801034,"MAR 16, 2019",ATL @ BOS,L,31,10,17,0.588,...,3,4,4,2,0,6,2,26,-16,2
12,22018,1629027,0021801016,"MAR 13, 2019",ATL vs. MEM,W,25,8,12,0.667,...,3,3,8,1,0,0,1,22,25,1
13,22018,1629027,0021800995,"MAR 10, 2019",ATL vs. NOP,W,31,2,14,0.143,...,3,5,10,0,0,2,2,10,-7,1
14,22018,1629027,0021800987,"MAR 09, 2019",ATL vs. BKN,L,29,4,14,0.286,...,7,10,11,1,0,2,3,23,13,1
15,22018,1629027,0021800968,"MAR 06, 2019",ATL vs. SAS,L,32,8,24,0.333,...,4,6,4,1,0,2,2,22,-16,1
16,22018,1629027,0021800953,"MAR 04, 2019",ATL @ MIA,L,30,4,11,0.364,...,1,3,8,1,0,8,1,14,2,1
17,22018,1629027,0021800946,"MAR 03, 2019",ATL @ CHI,W,18,6,9,0.667,...,2,2,5,0,0,2,0,18,11,1
18,22018,1629027,0021800928,"MAR 01, 2019",ATL vs. CHI,L,56,17,33,0.515,...,7,8,16,1,1,9,2,49,-9,1
19,22018,1629027,0021800912,"FEB 27, 2019",ATL vs. MIN,W,43,9,22,0.409,...,7,8,10,0,0,3,2,36,21,1
20,22018,1629027,0021800903,"FEB 25, 2019",ATL @ HOU,L,41,12,23,0.522,...,1,1,8,0,0,4,2,36,-1,1
21,22018,1629027,0021800883,"FEB 23, 2019",ATL vs. PHX,W,34,5,14,0.357,...,2,2,8,1,0,2,2,23,13,1
22,22018,1629027,0021800877,"FEB 22, 2019",ATL vs. DET,L,37,11,23,0.478,...,3,3,10,0,0,4,2,30,-1,1
23,22018,1629027,0021800865,"FEB 14, 2019",ATL vs. NYK,L,31,6,19,0.316,...,4,6,11,2,0,3,2,16,-11,1
24,22018,1629027,0021800848,"FEB 12, 2019",ATL vs. LAL,W,38,6,19,0.316,...,6,6,14,1,1,6,2,22,11,1
25,22018,1629027,0021800837,"FEB 10, 2019",ATL vs. ORL,L,26,3,9,0.333,...,4,5,7,0,0,3,2,13,-25,1
26,22018,1629027,0021800827,"FEB 09, 2019",ATL vs. CHA,L,28,8,15,0.533,...,1,1,11,2,0,4,1,20,-10,1
27,22018,1629027,0021800813,"FEB 07, 2019",ATL vs. TOR,L,29,7,14,0.500,...,4,5,5,1,0,4,2,19,-23,1
28,22018,1629027,0021800791,"FEB 04, 2019",ATL @ WAS,W,27,2,13,0.154,...,4,4,10,0,0,1,1,10,3,1
29,22018,1629027,0021800784,"FEB 02, 2019",ATL @ PHX,W,34,9,21,0.429,...,6,7,8,0,0,4,0,27,-3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,22018,1629027,0021800452,"DEC 18, 2018",ATL vs. WAS,W,26,5,11,0.455,...,3,3,4,1,0,5,2,19,2,1
52,22018,1629027,0021800436,"DEC 16, 2018",ATL @ BKN,L,29,4,10,0.400,...,1,2,10,1,0,3,2,13,-7,1
53,22018,1629027,0021800420,"DEC 14, 2018",ATL @ BOS,L,23,2,11,0.182,...,0,3,3,0,1,3,2,9,-26,1
54,22018,1629027,0021800412,"DEC 12, 2018",ATL @ DAL,L,35,11,19,0.579,...,0,0,10,2,0,2,3,24,1,1
55,22018,1629027,0021800380,"DEC 08, 2018",ATL vs. DEN,W,32,3,12,0.250,...,1,2,4,0,1,4,3,9,3,1
56,22018,1629027,0021800357,"DEC 05, 2018",ATL vs. WAS,L,33,4,13,0.308,...,1,2,5,2,0,6,2,14,-16,1
57,22018,1629027,0021800344,"DEC 03, 2018",ATL vs. GSW,L,25,8,20,0.400,...,0,0,3,0,0,7,1,20,-3,1
58,22018,1629027,0021800325,"NOV 30, 2018",ATL @ OKC,L,28,4,15,0.267,...,3,4,8,0,0,2,1,9,-17,1
59,22018,1629027,0021800306,"NOV 28, 2018",ATL @ CHA,L,28,7,19,0.368,...,2,3,4,2,1,5,1,18,-6,1
60,22018,1629027,0021800302,"NOV 27, 2018",ATL @ MIA,W,31,5,12,0.417,...,5,5,10,1,1,3,0,17,1,1
61,22018,1629027,0021800288,"NOV 25, 2018",ATL vs. CHA,W,30,6,18,0.333,...,2,2,5,2,1,5,0,18,3,1
62,22018,1629027,0021800268,"NOV 23, 2018",ATL vs. BOS,L,19,2,7,0.286,...,0,0,2,0,1,3,0,5,-35,1
63,22018,1629027,0021800254,"NOV 21, 2018",ATL vs. TOR,L,22,2,7,0.286,...,1,1,5,1,0,1,0,6,-16,1
64,22018,1629027,0021800243,"NOV 19, 2018",ATL vs. LAC,L,37,8,22,0.364,...,3,3,17,0,0,6,1,25,-7,1
65,22018,1629027,0021800226,"NOV 17, 2018",ATL @ IND,L,24,3,11,0.273,...,1,1,4,1,0,3,2,9,-14,1
66,22018,1629027,0021800214,"NOV 15, 2018",ATL @ DEN,L,27,2,11,0.182,...,2,2,5,1,0,5,1,6,-22,1
67,22018,1629027,0021800201,"NOV 13, 2018",ATL @ GSW,L,28,2,12,0.167,...,5,5,9,3,0,3,2,4,-11,1
68,22018,1629027,0021800189,"NOV 11, 2018",ATL @ LAL,L,35,8,18,0.444,...,1,2,12,1,1,4,2,20,15,1
69,22018,1629027,0021800169,"NOV 09, 2018",ATL vs. DET,L,23,4,9,0.444,...,3,4,5,0,0,6,1,16,-18,1
70,22018,1629027,0021800155,"NOV 07, 2018",ATL vs. NYK,L,31,6,19,0.316,...,4,5,8,0,0,2,2,15,3,1
71,22018,1629027,0021800149,"NOV 06, 2018",ATL @ CHA,L,30,8,19,0.421,...,2,3,10,0,0,6,0,18,-15,1
72,22018,1629027,0021800128,"NOV 03, 2018",ATL vs. MIA,W,31,9,19,0.474,...,4,6,15,0,1,5,0,24,5,1
73,22018,1629027,0021800114,"NOV 01, 2018",ATL vs. SAC,L,27,6,13,0.462,...,3,3,10,0,0,8,3,14,-11,1
74,22018,1629027,0021800097,"OCT 30, 2018",ATL @ CLE,L,31,9,13,0.692,...,1,1,4,0,0,3,2,24,-29,1
75,22018,1629027,0021800088,"OCT 29, 2018",ATL @ PHI,L,29,5,13,0.385,...,2,2,8,0,0,0,1,11,-14,1
76,22018,1629027,0021800076,"OCT 27, 2018",ATL vs. CHI,L,30,3,12,0.250,...,2,3,4,2,0,5,0,13,-21,1
77,22018,1629027,0021800052,"OCT 24, 2018",ATL vs. DAL,W,26,3,12,0.250,...,3,4,5,0,1,5,4,17,-6,1
78,22018,1629027,0021800036,"OCT 21, 2018",ATL @ CLE,W,38,13,23,0.565,...,2,2,11,1,0,1,2,35,19,1
79,22018,1629027,0021800020,"OCT 19, 2018",ATL @ MEM,L,33,7,18,0.389,...,1,2,9,1,1,3,2,20,-11,1
80,22018,1629027,0021800007,"OCT 17, 2018",ATL @ NYK,L,33,5,14,0.357,...,6,6,5,0,0,4,4,14,-20,1

### Available Methods
* info()

## PlayerGeneralSplits
Uses: player stats segmented by wins, losses, poition, rest, etc

In [76]:
player.PlayerGeneralSplits(trae_id, season = '2018-19').days_rest()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Days Rest,0 Days Rest,12,5,7,0.417,31.1,6.7,15.6,0.428,...,6,4,4,4,6,5,3,2,27,0 Days Rest
1,Days Rest,1 Days Rest,50,19,31,0.380,31.0,6.2,15.2,0.406,...,5,6,5,6,4,3,1,2,27,1 Days Rest
2,Days Rest,2 Days Rest,14,5,9,0.357,29.1,6.9,15.4,0.449,...,3,5,3,2,3,4,2,1,27,2 Days Rest
3,Days Rest,3 Days Rest,2,0,2,0.000,34.6,8.5,18.0,0.472,...,4,1,6,3,5,6,4,2,27,3 Days Rest
4,Days Rest,4 Days Rest,2,0,2,0.000,33.4,5.5,16.0,0.344,...,1,2,1,5,1,2,4,2,27,4 Days Rest
5,Days Rest,6+ Days Rest,1,0,1,0.000,36.7,11.0,23.0,0.478,...,1,2,2,1,1,1,4,2,27,6+ Days Rest

### Available Methods
* days_rest()
* location()
* month()
* pre_post_all_star()
* starting_position()
* win_losses()

## PlayerInGameSplits
Uses: player stats by quarter/half and margins

In [78]:
player.PlayerGeneralSplits(trae_id, season = '2018-19').days_rest()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Days Rest,0 Days Rest,12,5,7,0.417,31.1,6.7,15.6,0.428,...,6,4,4,4,6,5,3,2,27,0 Days Rest
1,Days Rest,1 Days Rest,50,19,31,0.380,31.0,6.2,15.2,0.406,...,5,6,5,6,4,3,1,2,27,1 Days Rest
2,Days Rest,2 Days Rest,14,5,9,0.357,29.1,6.9,15.4,0.449,...,3,5,3,2,3,4,2,1,27,2 Days Rest
3,Days Rest,3 Days Rest,2,0,2,0.000,34.6,8.5,18.0,0.472,...,4,1,6,3,5,6,4,2,27,3 Days Rest
4,Days Rest,4 Days Rest,2,0,2,0.000,33.4,5.5,16.0,0.344,...,1,2,1,5,1,2,4,2,27,4 Days Rest
5,Days Rest,6+ Days Rest,1,0,1,0.000,36.7,11.0,23.0,0.478,...,1,2,2,1,1,1,4,2,27,6+ Days Rest

### Available Methods
* by_actual_margin()
* by_half()
* by_period()
* by_score_margin()

## PlayerLastNGamesSplits
Uses: player stats for last x games

In [80]:
player.PlayerLastNGamesSplits(trae_id, season= '2018-19').last10()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Last 10 Games,2018-19,10,5,5,0.5,32.3,8.3,19.1,0.435,...,1,1,1,1,1,1,1,1,36,2018-19

### Available Methods
* gamenumber()
* last10()
* last15()
* last20()
* last5()

## PlayerList
Uses: List of all players for a season

In [81]:
player.PlayerList(league_id = '00', season= '2018-19', only_current=1).info().head(2)

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,203518,"Abrines, Alex",Alex Abrines,0,2016,2018,alex_abrines,0,,,,,Y,00
1,203112,"Acy, Quincy",Quincy Acy,0,2012,2018,quincy_acy,0,,,,,Y,11

### Available Methods
* info()

## PlayerOpponentSplits
Uses: Player stats vs division, conference, or opponent

In [82]:
player.PlayerOpponentSplits(trae_id, season= '2018-19').by_conference()

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,vs. Conference,East,51,16,35,0.314,30.2,6.1,14.6,0.419,...,2,2,2,2,2,2,1,1,41,East
1,vs. Conference,West,30,13,17,0.433,32.1,7.1,17.1,0.417,...,1,1,1,1,1,1,2,2,41,West

### Available Methods
* by_conference()
* by_division()
* by_opponent()

## PlayerPassTracking
Uses: Stats based on passes made/received by player

In [83]:
player.PlayerPassTracking(trae_id, season='2018-19').passes_made()

,PLAYER_ID,PLAYER_NAME_LAST_FIRST,TEAM_NAME,TEAM_ID,TEAM_ABBREVIATION,PASS_TYPE,G,PASS_TO,PASS_TEAMMATE_PLAYER_ID,FREQUENCY,...,AST,FGM,FGA,FG_PCT,FG2M,FG2A,FG2_PCT,FG3M,FG3A,FG3_PCT
0,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Humphries, Isaac",1629353,0.000,...,0.00,0.00,0.02,0.000,0.00,0.01,0.000,0.00,0.01,0.000
1,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Adams, Jaylen",1629121,0.002,...,0.00,0.00,0.02,0.000,0.00,0.00,NaN,0.00,0.02,0.000
2,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Spellman, Omari",1629016,0.047,...,0.37,0.38,0.83,0.463,0.20,0.31,0.640,0.19,0.52,0.357
3,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Huerter, Kevin",1628989,0.134,...,0.84,1.17,2.80,0.419,0.60,1.31,0.462,0.57,1.49,0.380
4,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Dorsey, Tyler",1628416,0.007,...,0.02,0.04,0.16,0.231,0.02,0.06,0.400,0.01,0.10,0.125
5,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Collins, John",1628381,0.200,...,2.00,2.12,3.88,0.548,1.80,2.94,0.613,0.32,0.94,0.342
6,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Poythress, Alex",1627816,0.017,...,0.11,0.11,0.25,0.450,0.07,0.19,0.400,0.04,0.06,0.600
7,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Hamilton, Daniel",1627772,0.004,...,0.02,0.04,0.11,0.333,0.01,0.04,0.333,0.02,0.07,0.333
8,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Bembry, DeAndre'",1627761,0.063,...,0.28,0.37,1.10,0.337,0.31,0.72,0.431,0.06,0.38,0.161
9,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Prince, Taurean",1627752,0.098,...,0.77,1.01,2.33,0.434,0.43,0.91,0.473,0.58,1.42,0.409
10,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Davis, Deyonta",1627738,0.003,...,0.07,0.07,0.07,1.000,0.07,0.07,1.000,0.00,0.00,NaN
11,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Anderson, Justin",1626147,0.015,...,0.12,0.14,0.33,0.407,0.05,0.12,0.400,0.09,0.21,0.412
12,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Dedmon, Dewayne",203473,0.122,...,1.19,1.25,2.60,0.479,0.70,1.16,0.606,0.54,1.44,0.376
13,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Len, Alex",203458,0.093,...,0.98,1.02,2.21,0.464,0.77,1.43,0.534,0.26,0.78,0.333
14,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Bazemore, Kent",203145,0.080,...,0.47,0.54,1.60,0.338,0.27,0.80,0.338,0.27,0.80,0.338
15,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Plumlee, Miles",203101,0.010,...,0.11,0.12,0.23,0.526,0.12,0.23,0.526,0.00,0.00,NaN
16,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Lin, Jeremy",202391,0.014,...,0.05,0.07,0.17,0.429,0.05,0.10,0.500,0.02,0.07,0.333
17,1629027,"Young, Trae",Atlanta Hawks,1610612737,ATL,made,81,"Carter, Vince",1713,0.090,...,0.60,0.70,1.67,0.422,0.26,0.52,0.500,0.44,1.15,0.387

### Available Methods
* passes_made()
* passes_received()

## PlayerPerformanceSplits
Uses: player stats based on scoring differentials

In [84]:
player.PlayerPerformanceSplits(trae_id, season= '2018-19').points_against()

,GROUP_SET,GROUP_VALUE_ORDER,GROUP_VALUE,GROUP_VALUE_2,GP,W,L,W_PCT,MIN,FGM,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,Points Against,NaN,W,100+ Points,26,26,0,1.0,31.5,6.9,...,3,3,2,1,2,1,1,2,67,None
1,Points Against,NaN,W,80-89 Points,1,1,0,1.0,30.4,6.0,...,4,4,4,2,1,3,3,2,65,None
2,Points Against,NaN,W,90-99 Points,2,2,0,1.0,31.6,3.5,...,1,1,5,5,3,4,3,2,66,None
3,Points Against,0.0,W,All,29,29,0,1.0,31.5,6.7,...,1,2,1,1,1,1,1,2,61,None
4,Points Against,NaN,L,100+ Points,50,0,50,0.0,30.7,6.5,...,2,2,3,3,4,2,1,1,72,None
5,Points Against,NaN,L,90-99 Points,2,0,2,0.0,27.1,3.0,...,4,4,1,4,5,5,3,2,71,None
6,Points Against,0.0,L,All,52,0,52,0.0,30.6,6.4,...,2,1,2,2,2,2,1,1,68,None

### Available Methods
* points_against()
* poinst_scored()
* score_differential()

## PlayerProfile
Uses: Career information for players

In [86]:
player.PlayerProfile(trae_id).season_highs()

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,RANK_PG_MIN,RANK_PG_FGM,...,RANK_FT_PCT,RANK_PG_OREB,RANK_PG_DREB,RANK_PG_REB,RANK_PG_AST,RANK_PG_STL,RANK_PG_BLK,RANK_PG_TOV,RANK_PG_PTS,RANK_PG_EFF
0,1629027,2018-19,00,1610612737,ATL,NR,NR,NR,61,43,...,47,132,153,151,4,82,202,4,34,52

### Available Methods
* career_highs()
* next_game()
* season_highs()

## PlayerReboundLogTracking
Uses: every rebound by every player

In [93]:
#player.PlayerReboundLogTracking(trae_id)
#currently giving json error

### Available Methods
* overall()

## PlayerReboundTracking
Uses: player rebounding by segment

In [94]:
player.PlayerReboundTracking(trae_id, season= '2018-19').num_contested_rebounding()

,PLAYER_ID,PLAYER_NAME_LAST_FIRST,SORT_ORDER,G,REB_NUM_CONTESTING_RANGE,REB_FREQUENCY,OREB,DREB,REB,C_OREB,C_DREB,C_REB,C_REB_PCT,UC_OREB,UC_DREB,UC_REB,UC_REB_PCT
0,1629027,"Young, Trae",1,81,0 Contesting Rebounders,0.877,0.57,2.69,3.26,0.00,0.00,0.00,0.0,0.57,2.69,3.26,1.0
1,1629027,"Young, Trae",2,81,1 Contesting Rebounder,0.120,0.19,0.26,0.44,0.19,0.26,0.44,1.0,0.00,0.00,0.00,0.0
2,1629027,"Young, Trae",3,81,2+ Contesting Rebounders,0.007,0.02,0.00,0.02,0.02,0.00,0.02,1.0,0.00,0.00,0.00,0.0

### Available Methods
* num_contested_rebounding()
* rebound_distance_rebounding()
* shot_distance_rebounding()
* shot_type_rebounding()

## PlayerShootingSplits
Uses: player shooting stats segmented by shot type, distance, etc

In [95]:
player.PlayerShootingSplits(trae_id, season = '2018-19').shot_5ft()

,GROUP_SET,GROUP_VALUE,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,EFG_PCT,BLKA,...,EFG_PCT_RANK,BLKA_RANK,PCT_AST_2PM_RANK,PCT_UAST_2PM_RANK,PCT_AST_3PM_RANK,PCT_UAST_3PM_RANK,PCT_AST_FGM_RANK,PCT_UAST_FGM_RANK,CFID,CFPARAMS
0,Shot Distance (5ft),Less Than 5 ft.,209,393,0.532,0,0,0.000,0.532,64,...,3,9,2,4,5,5,6,3,47,Less Than 5 ft.
1,Shot Distance (5ft),5-9 ft.,53,118,0.449,0,0,0.000,0.449,17,...,6,8,3,3,5,5,7,2,47,5-9 ft.
2,Shot Distance (5ft),10-14 ft.,77,166,0.464,0,0,0.000,0.464,8,...,5,7,1,5,5,5,5,4,47,10-14 ft.
3,Shot Distance (5ft),15-19 ft.,22,63,0.349,0,0,0.000,0.349,3,...,8,5,4,2,5,5,8,1,47,15-19 ft.
4,Shot Distance (5ft),20-24 ft.,26,90,0.289,18,56,0.321,0.389,1,...,7,4,5,1,1,3,4,5,47,20-24 ft.
5,Shot Distance (5ft),25-29 ft.,113,355,0.318,113,355,0.318,0.477,5,...,4,6,6,6,3,2,2,7,47,25-29 ft.
6,Shot Distance (5ft),30-34 ft.,23,64,0.359,23,64,0.359,0.539,0,...,2,1,6,6,4,1,3,6,47,30-34 ft.
7,Shot Distance (5ft),35-39 ft.,2,5,0.400,2,5,0.400,0.600,0,...,1,1,6,6,1,3,1,8,47,35-39 ft.
8,Shot Distance (5ft),40+ ft.,0,2,0.000,0,2,0.000,0.000,0,...,9,1,6,6,5,5,9,9,47,40+ ft.

### Available Methods
* assisted_by()
* assisted_shots()
* shot_5ft()
* shot_8ft()
* shot_areas()
* shot_types_details()
* shot_types_summary()

## PlayerShotLogTracking
Uses: every shot for every player

In [97]:
#player.PlayerShotLogTracking(trae_id, season= '2018-19').overall()
# same json error as rebound log tracking. may be deprecated

### Available Methods
* overall()

## PlayerShotTracking
Uses: player shot tracking data

In [98]:
player.PlayerShotTracking(trae_id, season= '2018-19').closest_defender_shooting()

,PLAYER_ID,PLAYER_NAME_LAST_FIRST,SORT_ORDER,GP,G,CLOSE_DEF_DIST_RANGE,FGA_FREQUENCY,FGM,FGA,FG_PCT,EFG_PCT,FG2A_FREQUENCY,FG2M,FG2A,FG2_PCT,FG3A_FREQUENCY,FG3M,FG3A,FG3_PCT
0,1629027,"Young, Trae",1,81,54,0-2 Feet - Very Tight,0.082,0.40,1.27,0.311,0.316,0.079,0.38,1.22,0.313,0.003,0.01,0.05,0.250
1,1629027,"Young, Trae",2,81,80,2-4 Feet - Tight,0.378,2.69,5.86,0.459,0.464,0.354,2.63,5.49,0.479,0.024,0.06,0.37,0.167
2,1629027,"Young, Trae",3,81,80,4-6 Feet - Open,0.272,1.81,4.22,0.430,0.497,0.146,1.25,2.27,0.549,0.126,0.57,1.95,0.291
3,1629027,"Young, Trae",4,81,79,6+ Feet - Wide Open,0.268,1.58,4.16,0.380,0.534,0.037,0.30,0.58,0.511,0.231,1.28,3.58,0.359

### Available Methods
* closest_defender_shooting()
* cloest_defender_shooting_long()
* dribble_shooting()
* general_shooting()
* shot_clock_shooting()
* touch_time_shooting()

## PlayerSummary
Uses: Basic player stats- heigh, weight, pts, reb, etc

In [99]:
player.PlayerSummary(trae_id).headline_stats()

   PLAYER_ID PLAYER_NAME TimeFrame   PTS  AST  REB    PIE
0    1629027  Trae Young   2018-19  19.1  8.1  3.7  0.119

### Available Methods
* headline_stats()
* info()

## PlayerVsPlayer
Uses: player stats vs another player

In [123]:
dal_id = 1610612742
dal_roster = team.TeamCommonRoster(dal_id, season= '2018-19').roster()
luka_id = dal_roster[dal_roster.PLAYER == "Luka Doncic"]['PLAYER_ID']

In [124]:
player.PlayerVsPlayer(trae_id, luka_id, season='2018-19').overall()

,GROUP_SET,GROUP_VALUE,PLAYER_ID,PLAYER_NAME,GP,W,L,W_PCT,MIN,FGM,...,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,CFID,CFPARAMS
0,Overall,Trae Young,1629027,Trae Young,81,29,52,0.358,30.9,6.5,...,0.9,0.2,1.2,1.7,5.3,19.1,-4.1,35.1,85,Trae Young
1,Overall,Luka Doncic,1629029,Luka Doncic,72,28,44,0.389,32.2,7.0,...,1.1,0.3,0.7,1.9,5.6,21.2,-1.6,40.3,85,Luka Doncic

### Available Methods
* on_off_court()
* overall()
* player_info()
* shot_area_off_court()
* shot_area_on_court()
* shot_area_overall()
* shot_distance_off_court()
* shot_distance_on_court()
* shot_distance_overall()
* vs_player_info()

## PlayerYearOverYearSplits
Uses: player stats over time

In [125]:
player.PlayerYearOverYearSplits(trae_id).by_year()

,GROUP_SET,GROUP_VALUE,TEAM_ID,TEAM_ABBREVIATION,MAX_GAME_DATE,GP,W,L,W_PCT,MIN,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,By Year,2018-19,1610612737,ATL,2019-04-10T00:00:00,81,29,52,0.358,30.9,...,1,1,1,1,1,1,1,1,264,2018-19

### Available Methods
* by_year()

## get_player
Uses: get a player id based on name

In [126]:
player.get_player(first_name = 'Lebron', last_name= 'James')

1944    2544
Name: PERSON_ID, dtype: int64

# Game Module

In [127]:
game_id = '0021800501'

## Boxscore
Uses: get box score stats for game

In [129]:
game.Boxscore(game_id).player_stats()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,FGM,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,2,...,3,1,4,0,1,0,0,3,6,-7.0
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,3,...,2,5,7,2,3,0,0,2,11,-14.0
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,3,...,2,8,10,2,1,1,1,5,7,-9.0
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,4,...,1,2,3,3,1,1,4,2,11,-14.0
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,9,...,2,3,5,4,0,1,1,3,20,-13.0
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,4,...,0,3,3,3,0,0,2,0,12,-4.0
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,2,...,0,4,4,0,0,0,0,1,7,-9.0
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,4,...,1,2,3,2,0,0,2,2,10,-7.0
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,3,...,0,0,0,2,1,0,1,0,8,-12.0
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,0,...,0,2,2,2,0,0,0,0,0,-7.0
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,0,...,0,1,1,0,0,0,1,1,0,-3.0
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,0,...,0,0,0,0,0,0,0,0,0,-3.0
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,1,...,0,0,0,0,0,0,0,1,4,-3.0
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,6,...,0,7,7,5,0,0,1,1,15,22.0
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,3,...,4,6,10,2,0,0,0,3,7,4.0
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,7,...,4,10,14,0,1,7,3,3,18,10.0
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,8,...,0,2,2,2,1,0,2,4,19,8.0
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,5,...,1,2,3,6,2,1,4,4,14,12.0
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,3,...,0,4,4,1,0,0,2,0,12,9.0
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,4,...,0,3,3,0,2,1,2,3,10,2.0
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,7,...,0,2,2,4,0,0,1,0,15,9.0
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,0,...,0,1,1,0,0,1,0,1,0,13.0
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,1,...,0,1,1,0,0,0,1,0,2,0.0
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,1,...,0,1,1,0,1,0,1,0,2,4.0
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,0,...,0,0,0,0,0,0,0,0,0,6.0
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,1,...,0,1,1,0,0,0,0,0,3,6.0

### Available Methods
* player_stats()
* team_starter_bench_stats()
* team_stats()

## BoxscoreAdvanced
Uses: Advanced metrics boxscore- ts_pct, e_usg_pct, e_pace, etc

In [130]:
game.BoxscoreAdvanced(game_id).sql_players_advanced()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,E_OFF_RATING,...,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,95.8,...,0.0,0.250,0.307,0.161,0.166,100.75,100.01,83.34,51,-0.019
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,92.1,...,0.0,0.667,0.709,0.099,0.101,102.10,101.08,84.23,69,0.142
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,84.8,...,7.1,0.300,0.322,0.190,0.192,105.03,105.77,88.14,56,0.068
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,89.8,...,17.4,0.321,0.349,0.238,0.243,101.94,101.74,84.78,72,0.000
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,93.2,...,3.8,0.476,0.476,0.262,0.269,101.35,100.76,83.97,72,0.105
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,99.0,...,13.3,0.444,0.558,0.273,0.276,101.15,100.55,83.79,41,0.140
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,107.8,...,0.0,0.417,0.509,0.156,0.159,96.76,96.16,80.14,38,0.071
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,100.1,...,16.7,0.667,0.644,0.294,0.303,99.51,102.41,85.34,32,0.104
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,96.3,...,14.3,1.000,1.000,0.161,0.166,100.04,98.86,82.38,29,0.149
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,97.6,...,0.0,0.000,0.000,0.103,0.109,103.54,105.85,88.21,27,0.019
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,102.0,...,100.0,0.000,0.000,0.167,0.170,97.92,108.00,90.00,6,-0.091
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,102.0,...,0.0,0.000,0.000,0.167,0.170,97.92,108.00,90.00,6,-0.091
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,102.0,...,0.0,1.500,1.064,0.333,0.340,97.92,108.00,90.00,6,0.182
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,124.9,...,6.7,0.833,0.833,0.127,0.133,98.43,100.09,83.41,70,0.178
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,113.9,...,0.0,0.600,0.595,0.130,0.135,99.29,101.68,84.73,40,0.143
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,105.9,...,17.6,0.700,0.645,0.215,0.224,101.85,103.01,85.84,71,0.198
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,119.9,...,8.3,0.500,0.481,0.301,0.317,98.93,101.70,84.75,66,0.042
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,107.9,...,18.2,0.545,0.568,0.222,0.229,99.49,101.08,84.23,65,0.107
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,125.2,...,13.3,0.400,0.492,0.212,0.231,99.30,100.65,83.87,60,0.060
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,98.9,...,25.0,0.833,0.833,0.154,0.162,104.47,103.92,86.60,46,0.111
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,129.0,...,7.1,0.833,0.833,0.233,0.249,104.50,105.06,87.55,38,0.220
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,139.7,...,0.0,0.000,0.000,0.000,0.000,111.59,114.87,95.73,15,0.022
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,90.1,...,33.3,0.500,0.500,0.150,0.152,99.54,96.39,80.32,17,0.045
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,93.5,...,50.0,1.000,1.000,0.083,0.094,109.39,113.05,94.21,22,0.133
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,180.0,...,0.0,0.000,0.000,0.167,0.200,114.74,127.74,106.45,6,-0.111
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,180.0,...,0.0,1.500,1.500,0.167,0.200,114.74,127.74,106.45,6,0.444

### Available Methods
* sql_players_advanced()
* sql_team_advanced()

## BoxscoreFourFactors
Uses: efg_pct, fta_rate, tm_tovpct, etc

In [131]:
game.BoxscoreFourFactors(game_id).sql_players_four_factors()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,OREB_PCT,OPP_EFG_PCT,OPP_FTA_RATE,OPP_TOV_PCT,OPP_OREB_PCT
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,0.402,0.275,0.059,0.290,0.632,0.395,0.247,0.263
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,0.414,0.266,0.115,0.270,0.673,0.346,0.215,0.208
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,0.390,0.300,0.106,0.200,0.598,0.366,0.230,0.190
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,0.408,0.292,0.124,0.263,0.623,0.316,0.183,0.233
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,0.418,0.269,0.097,0.256,0.632,0.316,0.206,0.241
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,0.516,0.313,0.169,0.118,0.554,0.189,0.100,0.211
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,0.500,0.257,0.128,0.263,0.635,0.216,0.101,0.278
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,0.520,0.360,0.125,0.071,0.565,0.161,0.064,0.250
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,0.500,0.304,0.138,0.083,0.643,0.214,0.126,0.250
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,0.500,0.286,0.150,0.083,0.659,0.227,0.079,0.111
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,0.625,0.500,0.170,0.000,0.900,0.000,0.000,0.000
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,0.625,0.500,0.170,0.000,0.900,0.000,0.000,0.000
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,0.625,0.500,0.170,0.000,0.900,0.000,0.000,0.000
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,0.664,0.276,0.147,0.259,0.422,0.379,0.090,0.206
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,0.603,0.235,0.177,0.313,0.469,0.469,0.078,0.150
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,0.591,0.327,0.189,0.233,0.408,0.262,0.126,0.263
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,0.647,0.373,0.158,0.231,0.483,0.267,0.123,0.303
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,0.622,0.367,0.203,0.231,0.393,0.262,0.094,0.278
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,0.716,0.295,0.194,0.200,0.482,0.236,0.085,0.250
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,0.586,0.229,0.242,0.235,0.474,0.237,0.131,0.095
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,0.647,0.147,0.108,0.214,0.554,0.357,0.160,0.067
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,0.750,0.250,0.070,0.000,0.300,0.200,0.155,0.000
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,0.438,0.250,0.113,0.222,0.538,0.231,0.245,0.286
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,0.500,0.176,0.148,0.111,0.342,0.158,0.148,0.250
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,0.900,0.000,0.000,0.000,0.333,0.667,0.205,0.000
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,0.900,0.000,0.000,0.000,0.333,0.667,0.205,0.000

### Available Methods
* sql_players_four_factors()
* sql_team_four_factors()

## BoxscoreMisc
Uses: pts in paint, off tov, etc

In [132]:
game.BoxscoreMisc(game_id).sql_players_misc()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PTS_OFF_TOV,...,PTS_FB,PTS_PAINT,OPP_PTS_OFF_TOV,OPP_PTS_2ND_CHANCE,OPP_PTS_FB,OPP_PTS_PAINT,BLK,BLKA,PF,PFD
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,1,...,0,4,3,8,4,26,0,3,3,3
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,2,...,0,2,9,8,6,32,0,1,2,2
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,2,...,0,6,7,6,6,28,1,2,5,2
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,4,...,5,6,11,12,6,38,1,1,2,3
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,2,...,2,10,7,12,6,34,1,1,3,1
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,0,...,0,6,6,8,4,24,0,0,0,3
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,0,...,0,2,4,10,2,24,0,0,1,1
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,0,...,0,8,5,8,2,26,0,1,2,2
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,3,...,3,2,4,6,2,20,0,0,0,1
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,0,...,0,0,5,2,2,20,0,1,0,0
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,0,...,0,0,3,0,0,6,0,0,1,0
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,0,...,0,0,3,0,0,6,0,0,0,0
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,0,...,0,0,3,0,0,6,0,0,1,1
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,2,...,0,6,9,12,2,30,0,0,1,1
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,0,...,0,6,10,6,5,14,0,0,3,1
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,2,...,2,14,9,10,7,34,7,1,3,8
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,2,...,4,10,11,10,10,36,0,1,4,4
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,3,...,0,4,9,10,4,32,1,1,4,1
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,0,...,2,2,9,14,6,30,0,0,0,2
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,0,...,0,0,8,8,6,16,1,0,3,0
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,0,...,0,12,5,5,6,14,0,0,0,1
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,0,...,0,0,0,0,0,6,1,0,1,1
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,0,...,0,2,0,0,2,6,0,0,0,0
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,2,...,0,2,0,0,2,8,0,0,0,1
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,0,...,0,0,0,0,0,2,0,0,0,0
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,3,...,0,0,0,0,0,2,0,0,0,0

### Available Methods
* sql_players_misc()
* sql_team_misc()

## BoxscoreScoring
Uses: scoring in paint, off tov, in paint, fts, etc

In [133]:
game.BoxscoreScoring(game_id).sql_players_scoring()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,PCT_FGA_2PT,...,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,0.875,...,0.000,0.333,0.167,0.667,1.000,0.000,0.000,0.000,1.000,0.000
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,0.500,...,0.000,0.273,0.182,0.182,0.000,1.000,1.000,0.000,0.667,0.333
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,1.000,...,0.000,0.143,0.286,0.857,1.000,0.000,0.000,0.000,1.000,0.000
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,0.786,...,0.455,0.182,0.364,0.545,0.333,0.667,1.000,0.000,0.500,0.500
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,0.762,...,0.100,0.000,0.100,0.500,0.286,0.714,0.500,0.500,0.333,0.667
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,1.000,...,0.000,0.333,0.000,0.500,0.500,0.500,0.000,0.000,0.500,0.500
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,0.500,...,0.000,0.286,0.000,0.286,1.000,0.000,1.000,0.000,1.000,0.000
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,0.833,...,0.000,0.200,0.000,0.800,0.750,0.250,0.000,0.000,0.750,0.250
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,0.250,...,0.375,0.000,0.375,0.250,0.000,1.000,0.500,0.500,0.333,0.667
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,0.333,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,0.000,...,0.000,0.250,0.000,0.000,0.000,0.000,0.000,1.000,0.000,1.000
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,0.444,...,0.000,0.000,0.133,0.400,0.333,0.667,0.333,0.667,0.333,0.667
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,0.800,...,0.000,0.143,0.000,0.857,0.667,0.333,0.000,0.000,0.667,0.333
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,1.000,...,0.111,0.222,0.111,0.778,0.429,0.571,0.000,0.000,0.429,0.571
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,0.722,...,0.211,0.053,0.105,0.526,0.333,0.667,0.000,1.000,0.250,0.750
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,0.636,...,0.000,0.143,0.214,0.286,0.333,0.667,0.500,0.500,0.400,0.600
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,0.200,...,0.167,0.333,0.000,0.167,1.000,0.000,0.000,1.000,0.333,0.667
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,0.333,...,0.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000,1.000,0.000
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,0.889,...,0.000,0.000,0.000,0.800,0.000,1.000,1.000,0.000,0.143,0.857
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,1.000,...,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,1.000,...,0.000,0.000,1.000,1.000,1.000,0.000,0.000,0.000,1.000,0.000
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,1.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,0.000,...,0.000,0.000,1.000,0.000,0.000,0.000,1.000,0.000,1.000,0.000

### Available Methods
* sql_players_scoring()
* sql_team_scoring()

## BoxscoreSummary
Uses: attendance, inactives, officials, game line info

In [141]:
game.BoxscoreSummary(game_id).game_summary()

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,WH_STATUS
0,2018-12-25T00:00:00,5,0021800501,3,Final,20181225/PORUTA,1610612762,1610612757,2018,4,,ESPN,Q4 - ESPN,1

### Available Methods
* available_video()
* game_info()
* game_summary()
* inactive_players()
* last_meeting()
* line_score()
* officials()
* other_stats()
* season_series()

## BoxscoreUsage
Uses: player and team usage stats- pct_blks, pct_ast, rebs, etc

In [142]:
game.BoxscoreUsage(game_id).sql_players_usage()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,MIN,USG_PCT,...,PCT_DREB,PCT_REB,PCT_AST,PCT_TOV,PCT_STL,PCT_BLK,PCT_BLKA,PCT_PF,PCT_PFD,PCT_PTS
0,0021800501,1610612757,POR,Portland,203090,Maurice Harkless,F,,24:43,0.166,...,0.071,0.174,0.000,0.000,0.167,0.000,0.429,0.250,0.273,0.122
1,0021800501,1610612757,POR,Portland,202329,Al-Farouq Aminu,F,,32:46,0.101,...,0.263,0.241,0.143,0.000,0.500,0.000,0.125,0.125,0.154,0.172
2,0021800501,1610612757,POR,Portland,203994,Jusuf Nurkic,C,,25:52,0.192,...,0.471,0.435,0.200,0.167,0.167,0.333,0.333,0.385,0.182,0.146
3,0021800501,1610612757,POR,Portland,203468,CJ McCollum,G,,33:44,0.243,...,0.087,0.091,0.231,0.444,0.167,0.333,0.111,0.133,0.214,0.169
4,0021800501,1610612757,POR,Portland,203081,Damian Lillard,G,,34:18,0.269,...,0.136,0.156,0.286,0.143,0.000,0.333,0.111,0.200,0.077,0.299
5,0021800501,1610612757,POR,Portland,202323,Evan Turner,,,19:20,0.276,...,0.200,0.176,0.300,0.286,0.000,0.000,0.000,0.000,0.429,0.293
6,0021800501,1610612757,POR,Portland,203086,Meyers Leonard,,,19:28,0.159,...,0.308,0.222,0.000,0.000,0.000,0.000,0.000,0.200,0.143,0.167
7,0021800501,1610612757,POR,Portland,1628380,Zach Collins,,,15:14,0.303,...,0.167,0.231,0.333,0.500,0.000,0.000,0.500,0.500,0.333,0.313
8,0021800501,1610612757,POR,Portland,203552,Seth Curry,,,14:34,0.166,...,0.000,0.000,0.286,0.250,1.000,0.000,0.000,0.000,0.200,0.286
9,0021800501,1610612757,POR,Portland,203917,Nik Stauskas,,,12:01,0.109,...,0.250,0.222,0.333,0.000,0.000,0.000,1.000,0.000,0.000,0.000
10,0021800501,1610612757,POR,Portland,1628403,Caleb Swanigan,,,2:40,0.170,...,1.000,1.000,0.000,1.000,0.000,0.000,0.000,0.500,0.000,0.000
11,0021800501,1610612757,POR,Portland,1627774,Jake Layman,,,2:40,0.170,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
12,0021800501,1610612757,POR,Portland,1627735,Wade Baldwin IV,,,2:40,0.340,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.500,1.000,0.667
13,0021800501,1610612762,UTA,Utah,204060,Joe Ingles,F,,32:51,0.133,...,0.259,0.206,0.357,0.100,0.000,0.000,0.000,0.071,0.077,0.176
14,0021800501,1610612762,UTA,Utah,202324,Derrick Favors,F,,18:53,0.135,...,0.353,0.455,0.182,0.000,0.000,0.000,0.000,0.333,0.125,0.156
15,0021800501,1610612762,UTA,Utah,203497,Rudy Gobert,C,,33:05,0.224,...,0.357,0.400,0.000,0.231,0.167,0.778,0.333,0.231,0.500,0.247
16,0021800501,1610612762,UTA,Utah,1628378,Donovan Mitchell,G,,31:09,0.317,...,0.087,0.069,0.167,0.200,0.200,0.000,0.500,0.308,0.286,0.250
17,0021800501,1610612762,UTA,Utah,201937,Ricky Rubio,G,,30:52,0.229,...,0.077,0.094,0.500,0.308,0.500,0.125,0.333,0.333,0.067,0.203
18,0021800501,1610612762,UTA,Utah,203109,Jae Crowder,,,27:54,0.231,...,0.190,0.160,0.100,0.182,0.000,0.000,0.000,0.000,0.250,0.169
19,0021800501,1610612762,UTA,Utah,2594,Kyle Korver,,,21:01,0.162,...,0.158,0.130,0.000,0.182,0.500,0.167,0.000,0.500,0.000,0.222
20,0021800501,1610612762,UTA,Utah,203957,Dante Exum,,,17:08,0.249,...,0.143,0.118,0.500,0.250,0.000,0.000,0.000,0.000,0.200,0.313
21,0021800501,1610612762,UTA,Utah,202327,Ekpe Udoh,,,5:51,0.000,...,0.143,0.143,0.000,0.000,0.000,1.000,0.000,0.500,0.500,0.000
22,0021800501,1610612762,UTA,Utah,200757,Thabo Sefolosha,,,8:13,0.152,...,0.200,0.143,0.000,0.500,0.000,0.000,0.000,0.000,0.000,0.125
23,0021800501,1610612762,UTA,Utah,1626220,Royce O'Neale,,,8:55,0.094,...,0.111,0.100,0.000,0.333,1.000,0.000,0.000,0.000,0.200,0.105
24,0021800501,1610612762,UTA,Utah,1627777,Georges Niang,,,2:04,0.200,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25,0021800501,1610612762,UTA,Utah,203526,Raul Neto,,,2:04,0.200,...,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.333

### Available Methods
* sql_players_usage()
* sql_team_usage()

## PlayByPlay
uses: text based play by play- similar to ESPN live updates online

In [144]:
game.PlayByPlay(game_id).info()

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
0,0021800501,2,12,0,1,10:46 PM,12:00,None,None,None,None,None
1,0021800501,4,10,0,1,10:46 PM,12:00,Jump Ball Gobert vs. Nurkic: Tip to Favors,None,None,None,None
2,0021800501,7,1,78,1,10:46 PM,11:39,Mitchell 9' Floating Jump Shot (2 PTS),None,None,0 - 2,2
3,0021800501,9,2,1,1,10:47 PM,11:21,None,None,MISS Lillard 25' 3PT Jump Shot,None,None
4,0021800501,10,4,0,1,10:47 PM,11:13,Favors REBOUND (Off:0 Def:1),None,None,None,None
5,0021800501,11,1,79,1,10:47 PM,11:12,Mitchell 9' Pullup Jump Shot (4 PTS),None,None,0 - 4,4
6,0021800501,12,2,101,1,10:47 PM,10:47,None,None,MISS McCollum 12' Driving Floating Jump Shot,None,None
7,0021800501,13,4,0,1,10:47 PM,10:44,Gobert REBOUND (Off:0 Def:1),None,None,None,None
8,0021800501,14,5,2,1,10:47 PM,10:38,Gobert Lost Ball Turnover (P1.T1),None,Nurkic STEAL (1 STL),None,None
9,0021800501,16,6,2,1,10:47 PM,10:33,Favors S.FOUL (P1.T1) (E.Malloy),None,None,None,None
10,0021800501,18,3,11,1,10:48 PM,10:33,None,None,Aminu Free Throw 1 of 2 (1 PTS),1 - 4,3
11,0021800501,19,3,12,1,10:48 PM,10:33,None,None,Aminu Free Throw 2 of 2 (2 PTS),2 - 4,2
12,0021800501,20,2,1,1,10:48 PM,10:23,MISS Ingles 24' 3PT Jump Shot,None,None,None,None
13,0021800501,21,4,0,1,10:49 PM,10:20,Favors REBOUND (Off:1 Def:1),None,None,None,None
14,0021800501,23,6,2,1,10:49 PM,10:20,None,None,Nurkic S.FOUL (P1.T1) (E.Malloy),None,None
15,0021800501,25,3,11,1,10:49 PM,10:20,MISS Favors Free Throw 1 of 2,None,None,None,None
16,0021800501,26,4,1,1,10:49 PM,10:20,JAZZ Rebound,None,None,None,None
17,0021800501,27,3,12,1,10:49 PM,10:20,Favors Free Throw 2 of 2 (1 PTS),None,None,2 - 5,3
18,0021800501,28,6,2,1,10:50 PM,10:11,Ingles S.FOUL (P1.T2) (L.Wood),None,None,None,None
19,0021800501,30,3,11,1,10:50 PM,10:11,None,None,MISS Harkless Free Throw 1 of 2,None,None
20,0021800501,31,4,1,1,10:50 PM,10:11,None,None,Trail Blazers Rebound,None,None
21,0021800501,32,3,12,1,10:50 PM,10:11,None,None,Harkless Free Throw 2 of 2 (1 PTS),3 - 5,2
22,0021800501,34,2,79,1,10:51 PM,9:59,MISS Mitchell 17' Pullup Jump Shot,None,None,None,None
23,0021800501,35,4,0,1,10:51 PM,9:57,None,None,McCollum REBOUND (Off:0 Def:1),None,None
24,0021800501,36,5,2,1,10:51 PM,9:47,Rubio STEAL (1 STL),None,McCollum Lost Ball Turnover (P1.T1),None,None
25,0021800501,39,6,2,1,10:51 PM,9:45,None,None,McCollum S.FOUL (P1.T2) (E.Malloy),None,None
26,0021800501,41,3,11,1,10:51 PM,9:45,MISS Gobert Free Throw 1 of 2,None,None,None,None
27,0021800501,42,4,1,1,10:51 PM,9:45,JAZZ Rebound,None,None,None,None
28,0021800501,43,3,12,1,10:52 PM,9:45,MISS Gobert Free Throw 2 of 2,None,None,None,None
29,0021800501,44,4,0,1,10:52 PM,9:43,None,None,Nurkic REBOUND (Off:0 Def:1),None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
448,0021800501,634,8,0,4,12:55 AM,2:40,None,None,SUB: Swanigan FOR Lillard,None,None
449,0021800501,635,8,0,4,12:55 AM,2:40,None,None,SUB: Collins FOR McCollum,None,None
450,0021800501,636,8,0,4,12:55 AM,2:40,None,None,SUB: Layman FOR Aminu,None,None
451,0021800501,637,8,0,4,12:55 AM,2:40,None,None,SUB: Stauskas FOR Nurkic,None,None
452,0021800501,638,8,0,4,12:55 AM,2:40,None,None,SUB: Baldwin IV FOR Harkless,None,None
453,0021800501,645,1,80,4,12:56 AM,2:21,None,None,Baldwin IV 24' 3PT Step Back Jump Shot (3 PTS),93 - 108,15
454,0021800501,646,6,1,4,12:57 AM,2:04,None,None,Baldwin IV P.FOUL (P1.T4) (J.Orr),None,None
455,0021800501,648,8,0,4,12:57 AM,2:04,SUB: Exum FOR Ingles,None,None,None,None
456,0021800501,649,8,0,4,12:57 AM,2:04,SUB: Niang FOR Rubio,None,None,None,None
457,0021800501,650,8,0,4,12:57 AM,2:04,SUB: Udoh FOR Gobert,None,None,None,None
458,0021800501,651,8,0,4,12:57 AM,2:04,SUB: O'Neale FOR Mitchell,None,None,None,None
459,0021800501,652,8,0,4,12:57 AM,2:04,SUB: Neto FOR Crowder,None,None,None,None
460,0021800501,658,1,6,4,12:57 AM,1:55,Exum 5' Driving Layup (11 PTS),None,None,93 - 110,17
461,0021800501,659,2,1,4,12:57 AM,1:47,None,None,MISS Stauskas 24' 3PT Jump Shot,None,None
462,0021800501,660,4,0,4,12:57 AM,1:43,Exum REBOUND (Off:0 Def:2),None,None,None,None
463,0021800501,661,1,78,4,12:58 AM,1:36,Exum 6' Floating Jump Shot (13 PTS),None,None,93 - 112,19
464,0021800501,662,6,4,4,12:58 AM,1:32,None,None,Swanigan OFF.Foul (P1) (L.Wood),None,None
465,0021800501,664,5,37,4,12:58 AM,1:32,None,None,Swanigan Offensive Foul Turnover (P1.T12),None,None
466,0021800501,665,1,1,4,12:58 AM,1:19,Neto 25' 3PT Jump Shot (3 PTS) (Exum 4 AST),None,None,93 - 115,22
467,0021800501,667,2,1,4,12:58 AM,1:11,None,None,MISS Layman 25' 3PT Jump Shot,None,None
468,0021800501,668,4,0,4,12:58 AM,1:08,Neto REBOUND (Off:0 Def:1),None,None,None,None
469,0021800501,669,2,6,4,12:58 AM,1:03,MISS Niang 5' Driving Layup,None,None,None,None
470,0021800501,670,4,0,4,12:58 AM,1:01,None,None,Swanigan REBOUND (Off:0 Def:1),None,None
471,0021800501,671,6,2,4,12:59 AM,0:54,Udoh S.FOUL (P1.PN) (E.Malloy),None,None,None,None
472,0021800501,673,3,11,4,12:59 AM,0:54,None,None,MISS Baldwin IV Free Throw 1 of 2,None,None
473,0021800501,674,4,1,4,12:59 AM,0:54,None,None,Trail Blazers Rebound,None,None
474,0021800501,675,3,12,4,12:59 AM,0:54,None,None,Baldwin IV Free Throw 2 of 2 (4 PTS),94 - 115,21
475,0021800501,676,1,6,4,1:00 AM,0:34,Exum 5' Driving Layup (15 PTS),None,None,94 - 117,23
476,0021800501,677,1,3,4,1:00 AM,0:17,None,None,Collins 6' Hook Shot (10 PTS),96 - 117,21
477,0021800501,678,13,0,4,1:00 AM,0:00,None,None,None,96 - 117,21

### Available Methods
* available_video()
* info()

## PlayerTracking
Uses: time played, average speed, distance, dfgm, dfga, etc

In [1]:
game.PlayerTracking(game_id).info()

NameError: name 'game' is not defined

### Available Methods
* info()